/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"
#undef uchar
/*
 * USER DEFINED HEADERS
 */
extern float sasum_();
extern int isamax_();
extern void scopy_();
extern float sdot_();
extern void saxpy_();
extern float snrm2_();
extern void srotg_();
extern void srot_();
extern void sscal_();
extern void sswap_();
extern void sgemv_();
extern void sger_();
extern void ssymv_();
extern void strsv_();
extern void sgemm_();
extern void ssymm_();
extern void strmm_();
extern void strsm_();



/* ---------------------------------------- */


/*
 * FUNCTION -blas-sasum
 */
extern_c float C__blas_sasum(index_t * L1_x)
{
TRACE_PUSH("C__blas_sasum"); MM_ENTER;
{
float L_Tmp0;
float * L_Tmp1;
L_Tmp1 = IND_BASE_TYPED((L1_x),float );
L_Tmp0 = (float)( sasum_((L1_x)->dim,(L_Tmp1),(L1_x)->mod));
TRACE_POP("C__blas_sasum");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION -blas-siamax
 */
extern_c double C__blas_siamax(index_t * L1_x)
{
TRACE_PUSH("C__blas_siamax"); MM_ENTER;
{
double L_Tmp0;
float * L_Tmp1;
L_Tmp1 = IND_BASE_TYPED((L1_x),float );
L_Tmp0 = ((int)( isamax_((L1_x)->dim,(L_Tmp1),(L1_x)->mod))-1);
TRACE_POP("C__blas_siamax");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION -blas-sclr!
 */
extern_c bool C__blas_sclrD(float L1_alpha,index_t * L1_u)
{
TRACE_PUSH("C__blas_sclrD"); MM_ENTER;
{
float * L_Tmp0;
L_Tmp0 = IND_BASE_TYPED((L1_u),float );
 int inca = 0; scopy_((L1_u)->dim, &(L1_alpha), &inca, (L_Tmp0), (L1_u)->mod);
TRACE_POP("C__blas_sclrD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-scopy
 */
extern_c bool C__blas_scopy(index_t * L1_u,index_t * L1_v)
{
TRACE_PUSH("C__blas_scopy"); MM_ENTER;
{
{
int L2_0_n;
float * L_Tmp3;
float * L_Tmp4;
{
double L3_1_a;
double L3_2_b;
RTERR_DIM(0 < 0 || 0 >= 1);
L3_1_a = (int)((L1_u)->dim[0]);
RTERR_DIM(0 < 0 || 0 >= 1);
L3_2_b = (int)((L1_v)->dim[0]);
 if ((L3_1_a<L3_2_b)) { 
L2_0_n = L3_1_a;
 } else { 
L2_0_n = L3_2_b;
 } 
}
L_Tmp3 = IND_BASE_TYPED((L1_u),float );
L_Tmp4 = IND_BASE_TYPED((L1_v),float );
 scopy_(&(L2_0_n), (L_Tmp3), (L1_u)->mod, (L_Tmp4), (L1_v)->mod);
}
TRACE_POP("C__blas_scopy");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-sdot
 */
extern_c float C__blas_sdot(index_t * L1_u,index_t * L1_v)
{
TRACE_PUSH("C__blas_sdot"); MM_ENTER;
{
float L_Tmp0;
float * L_Tmp1;
float * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 1);
 if (((int)((L1_u)->dim[0])!=(int)((L1_v)->dim[0]))) { 
lush_error("vectors have different lengths");
 } 
L_Tmp1 = IND_BASE_TYPED((L1_u),float );
L_Tmp2 = IND_BASE_TYPED((L1_v),float );
L_Tmp0 = (float)( sdot_((L1_u)->dim,(L_Tmp1),(L1_u)->mod,(L_Tmp2),(L1_v)->mod));
TRACE_POP("C__blas_sdot");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION -blas-saxpy!
 */
extern_c bool C__blas_saxpyD(float L1_alpha,index_t * L1_u,index_t * L1_v)
{
TRACE_PUSH("C__blas_saxpyD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
L_Tmp0 = IND_BASE_TYPED((L1_u),float );
L_Tmp1 = IND_BASE_TYPED((L1_v),float );
 saxpy_((L1_v)->dim, &(L1_alpha), (L_Tmp0), (L1_u)->mod, (L_Tmp1), (L1_v)->mod);
TRACE_POP("C__blas_saxpyD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-snrm2
 */
extern_c float C__blas_snrm2(index_t * L1_v)
{
TRACE_PUSH("C__blas_snrm2"); MM_ENTER;
{
float L_Tmp0;
float * L_Tmp1;
L_Tmp1 = IND_BASE_TYPED((L1_v),float );
L_Tmp0 = (float)( snrm2_((L1_v)->dim,(L_Tmp1),(L1_v)->mod));
TRACE_POP("C__blas_snrm2");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION -blas-srotg!
 */
extern_c bool C__blas_srotgD(index_t * L1_abcs)
{
TRACE_PUSH("C__blas_srotgD"); MM_ENTER;
{
float * L_Tmp0;
RTERR_DIM(0 < 0 || 0 >= 1);
 if ((1!=(L1_abcs)->mod[0])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
 if (((int)((L1_abcs)->dim[0])<4)) { 
lush_error("input array too short");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_abcs),float );
{
  float *dp = (L_Tmp0);
  srotg_(dp, dp+1, dp+2, dp+3);
  }
TRACE_POP("C__blas_srotgD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-srotg
 */
extern_c index_t * C__blas_srotg(float L1_a,float L1_b)
{
TRACE_PUSH("C__blas_srotg"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(1);
storage_t *L2_0_srg = new_storage(ST_FLOAT);
{
index_t * L2_1_cs;
(L2_0_array)->st = L2_0_srg;
Midx_init_dim1(L2_0_array, 4);
RTERR_DIM(L2_0_array->dim[0]<0);
Midx_maclear(L2_0_array, float );
L2_1_cs = L2_0_array;
RTERR_BOUND(0>=(L2_1_cs)->dim[0]);
IDX_PTR(L2_1_cs,float )[(L2_1_cs)->mod[0]*((int)0)] = L1_a;
RTERR_BOUND(1>=(L2_1_cs)->dim[0]);
IDX_PTR(L2_1_cs,float )[(L2_1_cs)->mod[0]*((int)1)] = L1_b;
C__blas_srotgD(L2_1_cs);
RTERR_GEN((((int)2)+((int)2) > ((int)(L2_1_cs)->dim[((int)0)])), "specified interval is too large");
Midx_narrow(L2_1_cs,((int)0),((int)2),((int)2),float );
L_Tmp0 = L2_1_cs;
}
TRACE_POP("C__blas_srotg");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION -blas-srot!
 */
extern_c bool C__blas_srotD(index_t * L1_x,index_t * L1_y,index_t * L1_cs)
{
TRACE_PUSH("C__blas_srotD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
float * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 1);
 if (((int)((L1_x)->dim[0])!=(int)((L1_y)->dim[0]))) { 
lush_error("x and y are of different length");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
 if (((int)((L1_cs)->dim[0])!=2)) { 
lush_error("<cs> is not a two-element vector");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_cs),float );
L_Tmp1 = IND_BASE_TYPED((L1_x),float );
L_Tmp2 = IND_BASE_TYPED((L1_y),float );
{
  float *cs = (L_Tmp0);
  srot_((L1_x)->dim,(L_Tmp1),(L1_x)->mod,(L_Tmp2),(L1_y)->mod,cs,cs+1);
  }
TRACE_POP("C__blas_srotD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-sscal!
 */
extern_c bool C__blas_sscalD(float L1_alpha,index_t * L1_u)
{
TRACE_PUSH("C__blas_sscalD"); MM_ENTER;
{
float * L_Tmp0;
L_Tmp0 = IND_BASE_TYPED((L1_u),float );
 sscal_((L1_u)->dim,&(L1_alpha),(L_Tmp0),(L1_u)->mod);
TRACE_POP("C__blas_sscalD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-sscal1!
 */
extern_c bool C__blas_sscal1D(index_t * L1_u)
{
TRACE_PUSH("C__blas_sscal1D"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
L_Tmp0 = IND_BASE_TYPED((L1_u),float );
L_Tmp1 = IND_BASE_TYPED((L1_u),float );
 
  float l = 1/snrm2_((L1_u)->dim,(L_Tmp0),(L1_u)->mod);
  sscal_((L1_u)->dim,&l,(L_Tmp1),(L1_u)->mod);
TRACE_POP("C__blas_sscal1D");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-sswap
 */
extern_c bool C__blas_sswap(index_t * L1_x,index_t * L1_y)
{
TRACE_PUSH("C__blas_sswap"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 1);
 if (((int)((L1_x)->dim[0])!=(int)((L1_y)->dim[0]))) { 
lush_error("x and y are of different length");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_x),float );
L_Tmp1 = IND_BASE_TYPED((L1_y),float );
 sswap_((L1_x)->dim,(L_Tmp0),(L1_x)->mod,(L_Tmp1),(L1_y)->mod);
TRACE_POP("C__blas_sswap");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-ssum
 */
extern_c double C__blas_ssum(index_t * L1_u)
{
TRACE_PUSH("C__blas_ssum"); MM_ENTER;
{
double L_Tmp0;
float * L_Tmp1;
 const int incv = 0; const float v = 1;
L_Tmp1 = IND_BASE_TYPED((L1_u),float );
L_Tmp0 = (double)( sdot_((L1_u)->dim,(L_Tmp1),(L1_u)->mod, &v , &incv));
TRACE_POP("C__blas_ssum");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION -blas-sgemv!
 */
extern_c bool C__blas_sgemvD(float L1_alpha,index_t * L1_A,index_t * L1_x,float L1_beta,index_t * L1_y)
{
TRACE_PUSH("C__blas_sgemvD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
float * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((int)((L1_x)->dim[0])!=(L1_A)->dim[1])) { 
lush_error("u does not match row length of A");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((int)((L1_y)->dim[0])!=(L1_A)->dim[0])) { 
lush_error("v does not match column length of A");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_A),float );
L_Tmp1 = IND_BASE_TYPED((L1_x),float );
L_Tmp2 = IND_BASE_TYPED((L1_y),float );
 sgemv_("T",(L1_A)->dim+1,(L1_A)->dim,&(L1_alpha),(L_Tmp0),(L1_A)->mod,(L_Tmp1),(L1_x)->mod,&(L1_beta),(L_Tmp2),(L1_y)->mod);
TRACE_POP("C__blas_sgemvD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-sgemv
 */
extern_c index_t * C__blas_sgemv(float L1_alpha,index_t * L1_A,index_t * L1_x)
{
TRACE_PUSH("C__blas_sgemv"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(1);
storage_t *L2_0_srg = new_storage(ST_FLOAT);
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((int)((L1_x)->dim[0])!=(L1_A)->dim[1])) { 
lush_error("u does not match row length of A");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
{
index_t * L2_1_y;
double L2_2_beta;
float * L_Tmp3;
float * L_Tmp4;
float * L_Tmp5;
(L2_0_array)->st = L2_0_srg;
RTERR_DIM(0 < 0 || 0 >= 2);
Midx_init_dim1(L2_0_array, (L1_A)->dim[0]);
RTERR_DIM(L2_0_array->dim[0]<0);
L2_1_y = L2_0_array;
L2_2_beta = 0;
L_Tmp3 = IND_BASE_TYPED((L1_A),float );
L_Tmp4 = IND_BASE_TYPED((L1_x),float );
L_Tmp5 = IND_BASE_TYPED((L2_1_y),float );
 sgemv_("T",(L1_A)->dim+1,(L1_A)->dim,&(L1_alpha),(L_Tmp3),(L1_A)->mod,(L_Tmp4),(L1_x)->mod,&(L2_2_beta),(L_Tmp5),(L2_1_y)->mod);
L_Tmp0 = L2_1_y;
}
TRACE_POP("C__blas_sgemv");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION -blas-sgevm!
 */
extern_c bool C__blas_sgevmD(float L1_alpha,index_t * L1_x,index_t * L1_A,float L1_beta,index_t * L1_y)
{
TRACE_PUSH("C__blas_sgevmD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
float * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((int)((L1_x)->dim[0])!=(L1_A)->dim[0])) { 
lush_error("u does not match column length of A");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((int)((L1_y)->dim[0])!=(L1_A)->dim[1])) { 
lush_error("v does not match row length of A");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_A),float );
L_Tmp1 = IND_BASE_TYPED((L1_x),float );
L_Tmp2 = IND_BASE_TYPED((L1_y),float );
 sgemv_("N",(L1_A)->dim+1,(L1_A)->dim,&(L1_alpha),(L_Tmp0),(L1_A)->mod,(L_Tmp1),(L1_x)->mod,&(L1_beta),(L_Tmp2),(L1_y)->mod);
TRACE_POP("C__blas_sgevmD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-sgevm
 */
extern_c index_t * C__blas_sgevm(float L1_alpha,index_t * L1_x,index_t * L1_A)
{
TRACE_PUSH("C__blas_sgevm"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(1);
storage_t *L2_0_srg = new_storage(ST_FLOAT);
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((int)((L1_x)->dim[0])!=(L1_A)->dim[0])) { 
lush_error("u does not match column length of A");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
{
index_t * L2_1_y;
double L2_2_beta;
float * L_Tmp3;
float * L_Tmp4;
float * L_Tmp5;
(L2_0_array)->st = L2_0_srg;
RTERR_DIM(1 < 0 || 1 >= 2);
Midx_init_dim1(L2_0_array, (L1_A)->dim[1]);
RTERR_DIM(L2_0_array->dim[0]<0);
L2_1_y = L2_0_array;
L2_2_beta = 0;
L_Tmp3 = IND_BASE_TYPED((L1_A),float );
L_Tmp4 = IND_BASE_TYPED((L1_x),float );
L_Tmp5 = IND_BASE_TYPED((L2_1_y),float );
 sgemv_("N",(L1_A)->dim+1,(L1_A)->dim,&(L1_alpha),(L_Tmp3),(L1_A)->mod,(L_Tmp4),(L1_x)->mod,&(L2_2_beta),(L_Tmp5),(L2_1_y)->mod);
L_Tmp0 = L2_1_y;
}
TRACE_POP("C__blas_sgevm");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION -blas-sger1!
 */
extern_c bool C__blas_sger1D(float L1_alpha,index_t * L1_u,index_t * L1_v,index_t * L1_A)
{
TRACE_PUSH("C__blas_sger1D"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
float * L_Tmp2;
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((int)((L1_u)->dim[0])!=(L1_A)->dim[0])) { 
lush_error("u does not match column length of A");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((int)((L1_v)->dim[0])!=(L1_A)->dim[1])) { 
lush_error("v does not match row length of A");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_v),float );
L_Tmp1 = IND_BASE_TYPED((L1_u),float );
L_Tmp2 = IND_BASE_TYPED((L1_A),float );
 sger_((L1_A)->dim+1,(L1_A)->dim,&(L1_alpha),(L_Tmp0),(L1_v)->mod,(L_Tmp1),(L1_u)->mod,(L_Tmp2),(L1_A)->mod);
TRACE_POP("C__blas_sger1D");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-ssymv!
 */
extern_c bool C__blas_ssymvD(float L1_alpha,index_t * L1_A,index_t * L1_x,float L1_beta,index_t * L1_y)
{
TRACE_PUSH("C__blas_ssymvD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
float * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((int)((L1_x)->dim[0])!=(L1_A)->dim[1])) { 
lush_error("u does not match row length of A");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((int)((L1_y)->dim[0])!=(L1_A)->dim[0])) { 
lush_error("v does not match column length of A");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_A),float );
L_Tmp1 = IND_BASE_TYPED((L1_x),float );
L_Tmp2 = IND_BASE_TYPED((L1_y),float );
 ssymv_("L",(L1_A)->dim,&(L1_alpha),(L_Tmp0),(L1_A)->mod,(L_Tmp1),(L1_x)->mod,&(L1_beta),(L_Tmp2),(L1_y)->mod);
TRACE_POP("C__blas_ssymvD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-ssymv
 */
extern_c index_t * C__blas_ssymv(float L1_alpha,index_t * L1_A,index_t * L1_x)
{
TRACE_PUSH("C__blas_ssymv"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(1);
storage_t *L2_0_srg = new_storage(ST_FLOAT);
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_A)->dim[0]==(L1_A)->dim[1]))) { 
lush_error("A not square");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((int)((L1_x)->dim[0])!=(L1_A)->dim[1])) { 
lush_error("u does not match row length of A");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
{
index_t * L2_1_y;
float L2_2_beta;
float * L_Tmp3;
float * L_Tmp4;
float * L_Tmp5;
(L2_0_array)->st = L2_0_srg;
RTERR_DIM(0 < 0 || 0 >= 2);
Midx_init_dim1(L2_0_array, (L1_A)->dim[0]);
RTERR_DIM(L2_0_array->dim[0]<0);
L2_1_y = L2_0_array;
L2_2_beta = 0;
L_Tmp3 = IND_BASE_TYPED((L1_A),float );
L_Tmp4 = IND_BASE_TYPED((L1_x),float );
L_Tmp5 = IND_BASE_TYPED((L2_1_y),float );
 ssymv_("L",(L1_A)->dim,&(L1_alpha),(L_Tmp3),(L1_A)->mod,(L_Tmp4),(L1_x)->mod,&(L2_2_beta),(L_Tmp5),(L2_1_y)->mod);
L_Tmp0 = L2_1_y;
}
TRACE_POP("C__blas_ssymv");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION -blas-sutsv!
 */
extern_c bool C__blas_sutsvD(index_t * L1_U,index_t * L1_x)
{
TRACE_PUSH("C__blas_sutsvD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_U)->dim[0]==(L1_U)->dim[1]))) { 
lush_error("U not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(0 < 0 || 0 >= 1);
 if (((L1_U)->dim[1]!=(int)((L1_x)->dim[0]))) { 
lush_error("arguments invalid for matrix-vector multiply");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_U),float );
L_Tmp1 = IND_BASE_TYPED((L1_x),float );
 strsv_("L","T","N",(L1_U)->dim,(L_Tmp0),(L1_U)->mod,(L_Tmp1),(L1_x)->mod);
TRACE_POP("C__blas_sutsvD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-sgemm!
 */
extern_c bool C__blas_sgemmD(float L1_alpha,index_t * L1_A,index_t * L1_B,float L1_beta,index_t * L1_C)
{
TRACE_PUSH("C__blas_sgemmD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
float * L_Tmp2;
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_C)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((L1_A)->dim[1]!=(L1_B)->dim[0])) { 
lush_error("matrices invalid for matrix-matrix multiply");
 } 
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((L1_A)->dim[0]!=(L1_C)->dim[0])) { 
lush_error("A and C not compatible");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((L1_B)->dim[1]!=(L1_C)->dim[1])) { 
lush_error("B and C not compatible");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_B),float );
L_Tmp1 = IND_BASE_TYPED((L1_A),float );
L_Tmp2 = IND_BASE_TYPED((L1_C),float );
 sgemm_("N","N",(L1_C)->dim+1,(L1_C)->dim,(L1_B)->dim,&(L1_alpha),(L_Tmp0),(L1_B)->mod,(L_Tmp1),(L1_A)->mod,&(L1_beta),(L_Tmp2),(L1_C)->mod);
TRACE_POP("C__blas_sgemmD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-sgemm
 */
extern_c bool C__blas_sgemm(float L1_alpha,index_t * L1_A,index_t * L1_B)
{
TRACE_PUSH("C__blas_sgemm"); MM_ENTER;
{
Midx_declare(L1_0_0_array, 2);
Msrg_declare(L1_1_0_srg);
bool L_Tmp2;
Midx_init(L1_0_0_array, 2);
Msrg_init(L1_1_0_srg, ST_FLOAT);
(L1_0_0_array)->st = L1_1_0_srg;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
Midx_init_dim2(L1_0_0_array, (L1_A)->dim[0],(L1_B)->dim[1]);
RTERR_DIM(L1_0_0_array->dim[0]<0);
RTERR_DIM(L1_0_0_array->dim[1]<0);
L_Tmp2 = (bool ) C__blas_sgemmD(L1_alpha, L1_A, L1_B, 0, L1_0_0_array);
Msrg_free(L1_1_0_srg);
TRACE_POP("C__blas_sgemm");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-ssymm!
 */
extern_c bool C__blas_ssymmD(float L1_alpha,index_t * L1_S,index_t * L1_B,float L1_beta,index_t * L1_C)
{
TRACE_PUSH("C__blas_ssymmD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
float * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_S)->dim[0]==(L1_S)->dim[1]))) { 
lush_error("S not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_S)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_S),float );
L_Tmp1 = IND_BASE_TYPED((L1_B),float );
L_Tmp2 = IND_BASE_TYPED((L1_C),float );
 ssymm_("R","L",(L1_C)->dim+1,(L1_C)->dim,&(L1_alpha),(L_Tmp0),(L1_S)->mod,(L_Tmp1),(L1_B)->mod,&(L1_beta),(L_Tmp2),(L1_C)->mod);
TRACE_POP("C__blas_ssymmD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-smsym!
 */
extern_c bool C__blas_smsymD(float L1_alpha,index_t * L1_B,index_t * L1_S,float L1_beta,index_t * L1_C)
{
TRACE_PUSH("C__blas_smsymD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
float * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_S)->dim[0]==(L1_S)->dim[1]))) { 
lush_error("S not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_S)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_S),float );
L_Tmp1 = IND_BASE_TYPED((L1_B),float );
L_Tmp2 = IND_BASE_TYPED((L1_C),float );
 ssymm_("L","L",(L1_C)->dim+1,(L1_C)->dim,&(L1_alpha),(L_Tmp0),(L1_S)->mod,(L_Tmp1),(L1_B)->mod,&(L1_beta),(L_Tmp2),(L1_C)->mod);
TRACE_POP("C__blas_smsymD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-sutmm!
 */
extern_c bool C__blas_sutmmD(float L1_alpha,index_t * L1_U,index_t * L1_B)
{
TRACE_PUSH("C__blas_sutmmD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_U)->dim[0]==(L1_U)->dim[1]))) { 
lush_error("U not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((L1_U)->dim[1]!=(L1_B)->dim[0])) { 
lush_error("matrices invalid for matrix-matrix multiply");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_U)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_U),float );
L_Tmp1 = IND_BASE_TYPED((L1_B),float );
 strmm_("R","L","N","N",(L1_B)->dim+1,(L1_B)->dim,&(L1_alpha),(L_Tmp0),(L1_U)->mod,(L_Tmp1),(L1_B)->mod);
TRACE_POP("C__blas_sutmmD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-smutm!
 */
extern_c bool C__blas_smutmD(float L1_alpha,index_t * L1_B,index_t * L1_U)
{
TRACE_PUSH("C__blas_smutmD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_U)->dim[0]==(L1_U)->dim[1]))) { 
lush_error("U not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((L1_B)->dim[1]!=(L1_U)->dim[0])) { 
lush_error("matrices invalid for matrix-matrix multiply");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_U)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_U),float );
L_Tmp1 = IND_BASE_TYPED((L1_B),float );
 strmm_("L","L","N","N",(L1_B)->dim+1,(L1_B)->dim,&(L1_alpha),(L_Tmp0),(L1_U)->mod,(L_Tmp1),(L1_B)->mod);
TRACE_POP("C__blas_smutmD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-sutsm!
 */
extern_c bool C__blas_sutsmD(float L1_alpha,index_t * L1_U,index_t * L1_B)
{
TRACE_PUSH("C__blas_sutsmD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_U)->dim[0]==(L1_U)->dim[1]))) { 
lush_error("U not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((L1_U)->dim[1]!=(L1_B)->dim[0])) { 
lush_error("matrices invalid for matrix-matrix multiply");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_U)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_U),float );
L_Tmp1 = IND_BASE_TYPED((L1_B),float );
 strsm_("R","L","N","N",(L1_B)->dim+1,(L1_B)->dim,&(L1_alpha),(L_Tmp0),(L1_U)->mod,(L_Tmp1),(L1_B)->mod);
TRACE_POP("C__blas_sutsmD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-smuts!
 */
extern_c bool C__blas_smutsD(float L1_alpha,index_t * L1_B,index_t * L1_U)
{
TRACE_PUSH("C__blas_smutsD"); MM_ENTER;
{
float * L_Tmp0;
float * L_Tmp1;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_U)->dim[0]==(L1_U)->dim[1]))) { 
lush_error("U not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((L1_B)->dim[1]!=(L1_U)->dim[0])) { 
lush_error("matrices invalid for matrix-matrix multiply");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_U)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_U),float );
L_Tmp1 = IND_BASE_TYPED((L1_B),float );
 strsm_("L","L","N","N",(L1_B)->dim+1,(L1_B)->dim,&(L1_alpha),(L_Tmp0),(L1_U)->mod,(L_Tmp1),(L1_B)->mod);
TRACE_POP("C__blas_smutsD");
MM_EXIT; return 0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB -blas-sasum
 */
DH(X__blas_sasum)
{
dharg ret;
ret.dh_float =  C__blas_sasum(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sasum
 */
DHDOC(K__blas_sasum_R59c70f6d,X__blas_sasum,"C__blas_sasum",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_FLOAT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-siamax
 */
DH(X__blas_siamax)
{
dharg ret;
ret.dh_double =  C__blas_siamax(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-siamax
 */
DHDOC(K__blas_siamax_Rf954c1ec,X__blas_siamax,"C__blas_siamax",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_DOUBLE,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sclr!
 */
DH(X__blas_sclrD)
{
dharg ret;
ret.dh_bool =  C__blas_sclrD(a[1].dh_float, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sclr!
 */
DHDOC(K__blas_sclrD_R478bc265,X__blas_sclrD,"C__blas_sclrD",0,0) = {
DH_FUNC(2),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-scopy
 */
DH(X__blas_scopy)
{
dharg ret;
ret.dh_bool =  C__blas_scopy(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-scopy
 */
DHDOC(K__blas_scopy_R450167d5,X__blas_scopy,"C__blas_scopy",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sdot
 */
DH(X__blas_sdot)
{
dharg ret;
ret.dh_float =  C__blas_sdot(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sdot
 */
DHDOC(K__blas_sdot_Ref192fd1,X__blas_sdot,"C__blas_sdot",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_FLOAT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-saxpy!
 */
DH(X__blas_saxpyD)
{
dharg ret;
ret.dh_bool =  C__blas_saxpyD(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-saxpy!
 */
DHDOC(K__blas_saxpyD_R2da86dcc,X__blas_saxpyD,"C__blas_saxpyD",0,0) = {
DH_FUNC(3),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-snrm2
 */
DH(X__blas_snrm2)
{
dharg ret;
ret.dh_float =  C__blas_snrm2(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-snrm2
 */
DHDOC(K__blas_snrm2_R59c70f6d,X__blas_snrm2,"C__blas_snrm2",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_FLOAT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-srotg!
 */
DH(X__blas_srotgD)
{
dharg ret;
ret.dh_bool =  C__blas_srotgD(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-srotg!
 */
DHDOC(K__blas_srotgD_Rf3df4769,X__blas_srotgD,"C__blas_srotgD",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-srotg
 */
DH(X__blas_srotg)
{
dharg ret;
ret.dh_idx_ptr =  C__blas_srotg(a[1].dh_float, a[2].dh_float);
return ret;
}

/*
 * DHDOC -blas-srotg
 */
DHDOC(K__blas_srotg_Recfe72e2,X__blas_srotg,"C__blas_srotg",0,0) = {
DH_FUNC(2),
DH_FLOAT,
DH_FLOAT,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_WRITE),
DH_FLOAT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-srot!
 */
DH(X__blas_srotD)
{
dharg ret;
ret.dh_bool =  C__blas_srotD(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-srot!
 */
DHDOC(K__blas_srotD_R28bd26ac,X__blas_srotD,"C__blas_srotD",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sscal!
 */
DH(X__blas_sscalD)
{
dharg ret;
ret.dh_bool =  C__blas_sscalD(a[1].dh_float, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sscal!
 */
DHDOC(K__blas_sscalD_R478bc265,X__blas_sscalD,"C__blas_sscalD",0,0) = {
DH_FUNC(2),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sscal1!
 */
DH(X__blas_sscal1D)
{
dharg ret;
ret.dh_bool =  C__blas_sscal1D(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sscal1!
 */
DHDOC(K__blas_sscal1D_Rf3df4769,X__blas_sscal1D,"C__blas_sscal1D",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sswap
 */
DH(X__blas_sswap)
{
dharg ret;
ret.dh_bool =  C__blas_sswap(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sswap
 */
DHDOC(K__blas_sswap_R450167d5,X__blas_sswap,"C__blas_sswap",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-ssum
 */
DH(X__blas_ssum)
{
dharg ret;
ret.dh_double =  C__blas_ssum(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-ssum
 */
DHDOC(K__blas_ssum_Rf954c1ec,X__blas_ssum,"C__blas_ssum",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_DOUBLE,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sgemv!
 */
DH(X__blas_sgemvD)
{
dharg ret;
ret.dh_bool =  C__blas_sgemvD(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_float, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sgemv!
 */
DHDOC(K__blas_sgemvD_R53eb298b,X__blas_sgemvD,"C__blas_sgemvD",0,0) = {
DH_FUNC(5),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sgemv
 */
DH(X__blas_sgemv)
{
dharg ret;
ret.dh_idx_ptr =  C__blas_sgemv(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sgemv
 */
DHDOC(K__blas_sgemv_R87988f93,X__blas_sgemv,"C__blas_sgemv",0,0) = {
DH_FUNC(3),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sgevm!
 */
DH(X__blas_sgevmD)
{
dharg ret;
ret.dh_bool =  C__blas_sgevmD(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_float, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sgevm!
 */
DHDOC(K__blas_sgevmD_R53eb298b,X__blas_sgevmD,"C__blas_sgevmD",0,0) = {
DH_FUNC(5),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sgevm
 */
DH(X__blas_sgevm)
{
dharg ret;
ret.dh_idx_ptr =  C__blas_sgevm(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sgevm
 */
DHDOC(K__blas_sgevm_R87988f93,X__blas_sgevm,"C__blas_sgevm",0,0) = {
DH_FUNC(3),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sger1!
 */
DH(X__blas_sger1D)
{
dharg ret;
ret.dh_bool =  C__blas_sger1D(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sger1!
 */
DHDOC(K__blas_sger1D_Rf9ef329e,X__blas_sger1D,"C__blas_sger1D",0,0) = {
DH_FUNC(4),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-ssymv!
 */
DH(X__blas_ssymvD)
{
dharg ret;
ret.dh_bool =  C__blas_ssymvD(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_float, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-ssymv!
 */
DHDOC(K__blas_ssymvD_R53eb298b,X__blas_ssymvD,"C__blas_ssymvD",0,0) = {
DH_FUNC(5),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-ssymv
 */
DH(X__blas_ssymv)
{
dharg ret;
ret.dh_idx_ptr =  C__blas_ssymv(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-ssymv
 */
DHDOC(K__blas_ssymv_R87988f93,X__blas_ssymv,"C__blas_ssymv",0,0) = {
DH_FUNC(3),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sutsv!
 */
DH(X__blas_sutsvD)
{
dharg ret;
ret.dh_bool =  C__blas_sutsvD(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sutsv!
 */
DHDOC(K__blas_sutsvD_R450167d5,X__blas_sutsvD,"C__blas_sutsvD",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sgemm!
 */
DH(X__blas_sgemmD)
{
dharg ret;
ret.dh_bool =  C__blas_sgemmD(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_float, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sgemm!
 */
DHDOC(K__blas_sgemmD_R53eb298b,X__blas_sgemmD,"C__blas_sgemmD",0,0) = {
DH_FUNC(5),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sgemm
 */
DH(X__blas_sgemm)
{
dharg ret;
ret.dh_bool =  C__blas_sgemm(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sgemm
 */
DHDOC(K__blas_sgemm_R2da86dcc,X__blas_sgemm,"C__blas_sgemm",0,0) = {
DH_FUNC(3),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-ssymm!
 */
DH(X__blas_ssymmD)
{
dharg ret;
ret.dh_bool =  C__blas_ssymmD(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_float, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-ssymm!
 */
DHDOC(K__blas_ssymmD_R53eb298b,X__blas_ssymmD,"C__blas_ssymmD",0,0) = {
DH_FUNC(5),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-smsym!
 */
DH(X__blas_smsymD)
{
dharg ret;
ret.dh_bool =  C__blas_smsymD(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_float, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-smsym!
 */
DHDOC(K__blas_smsymD_R53eb298b,X__blas_smsymD,"C__blas_smsymD",0,0) = {
DH_FUNC(5),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sutmm!
 */
DH(X__blas_sutmmD)
{
dharg ret;
ret.dh_bool =  C__blas_sutmmD(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sutmm!
 */
DHDOC(K__blas_sutmmD_R2da86dcc,X__blas_sutmmD,"C__blas_sutmmD",0,0) = {
DH_FUNC(3),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-smutm!
 */
DH(X__blas_smutmD)
{
dharg ret;
ret.dh_bool =  C__blas_smutmD(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-smutm!
 */
DHDOC(K__blas_smutmD_R2da86dcc,X__blas_smutmD,"C__blas_smutmD",0,0) = {
DH_FUNC(3),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-sutsm!
 */
DH(X__blas_sutsmD)
{
dharg ret;
ret.dh_bool =  C__blas_sutsmD(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-sutsm!
 */
DHDOC(K__blas_sutsmD_R2da86dcc,X__blas_sutsmD,"C__blas_sutsmD",0,0) = {
DH_FUNC(3),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-smuts!
 */
DH(X__blas_smutsD)
{
dharg ret;
ret.dh_bool =  C__blas_smutsD(a[1].dh_float, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-smuts!
 */
DHDOC(K__blas_smutsD_R2da86dcc,X__blas_smutsD,"C__blas_smutsD",0,0) = {
DH_FUNC(3),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_FLOAT,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_blas_float(void)
{
 dh_define("-blas-sasum", &K__blas_sasum_R59c70f6d); 
 dh_define("-blas-siamax", &K__blas_siamax_Rf954c1ec); 
 dh_define("-blas-sclr!", &K__blas_sclrD_R478bc265); 
 dh_define("-blas-scopy", &K__blas_scopy_R450167d5); 
 dh_define("-blas-sdot", &K__blas_sdot_Ref192fd1); 
 dh_define("-blas-saxpy!", &K__blas_saxpyD_R2da86dcc); 
 dh_define("-blas-snrm2", &K__blas_snrm2_R59c70f6d); 
 dh_define("-blas-srotg!", &K__blas_srotgD_Rf3df4769); 
 dh_define("-blas-srotg", &K__blas_srotg_Recfe72e2); 
 dh_define("-blas-srot!", &K__blas_srotD_R28bd26ac); 
 dh_define("-blas-sscal!", &K__blas_sscalD_R478bc265); 
 dh_define("-blas-sscal1!", &K__blas_sscal1D_Rf3df4769); 
 dh_define("-blas-sswap", &K__blas_sswap_R450167d5); 
 dh_define("-blas-ssum", &K__blas_ssum_Rf954c1ec); 
 dh_define("-blas-sgemv!", &K__blas_sgemvD_R53eb298b); 
 dh_define("-blas-sgemv", &K__blas_sgemv_R87988f93); 
 dh_define("-blas-sgevm!", &K__blas_sgevmD_R53eb298b); 
 dh_define("-blas-sgevm", &K__blas_sgevm_R87988f93); 
 dh_define("-blas-sger1!", &K__blas_sger1D_Rf9ef329e); 
 dh_define("-blas-ssymv!", &K__blas_ssymvD_R53eb298b); 
 dh_define("-blas-ssymv", &K__blas_ssymv_R87988f93); 
 dh_define("-blas-sutsv!", &K__blas_sutsvD_R450167d5); 
 dh_define("-blas-sgemm!", &K__blas_sgemmD_R53eb298b); 
 dh_define("-blas-sgemm", &K__blas_sgemm_R2da86dcc); 
 dh_define("-blas-ssymm!", &K__blas_ssymmD_R53eb298b); 
 dh_define("-blas-smsym!", &K__blas_smsymD_R53eb298b); 
 dh_define("-blas-sutmm!", &K__blas_sutmmD_R2da86dcc); 
 dh_define("-blas-smutm!", &K__blas_smutmD_R2da86dcc); 
 dh_define("-blas-sutsm!", &K__blas_sutsmD_R2da86dcc); 
 dh_define("-blas-smuts!", &K__blas_smutsD_R2da86dcc); 
}

int majver_blas_float = 50;
int minver_blas_float = 01;


#endif

