/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"
#undef uchar
/*
 * USER DEFINED HEADERS
 */
extern double dasum_();
extern int idamax_();
extern void dcopy_();
extern double ddot_();
extern void daxpy_();
extern double dnrm2_();
extern void drotg_();
extern void drot_();
extern void dscal_();
extern void dswap_();
extern void dgemv_();
extern void dger_();
extern void dsymv_();
extern void dtrsv_();
extern void dgemm_();
extern void dsymm_();
extern void dtrmm_();
extern void dtrsm_();



/* ---------------------------------------- */


/*
 * FUNCTION -blas-dasum
 */
extern_c double C__blas_dasum(index_t * L1_x)
{
TRACE_PUSH("C__blas_dasum"); MM_ENTER;
{
double L_Tmp0;
double * L_Tmp1;
L_Tmp1 = IND_BASE_TYPED((L1_x),double );
L_Tmp0 = (double)( dasum_((L1_x)->dim,(L_Tmp1),(L1_x)->mod));
TRACE_POP("C__blas_dasum");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION -blas-diamax
 */
extern_c double C__blas_diamax(index_t * L1_x)
{
TRACE_PUSH("C__blas_diamax"); MM_ENTER;
{
double L_Tmp0;
double * L_Tmp1;
L_Tmp1 = IND_BASE_TYPED((L1_x),double );
L_Tmp0 = ((int)( idamax_((L1_x)->dim,(L_Tmp1),(L1_x)->mod))-1);
TRACE_POP("C__blas_diamax");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION -blas-dclr!
 */
extern_c bool C__blas_dclrD(double L1_alpha,index_t * L1_u)
{
TRACE_PUSH("C__blas_dclrD"); MM_ENTER;
{
double * L_Tmp0;
L_Tmp0 = IND_BASE_TYPED((L1_u),double );
 int inca = 0; dcopy_((L1_u)->dim, &(L1_alpha), &inca, (L_Tmp0), (L1_u)->mod);
TRACE_POP("C__blas_dclrD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dcopy
 */
extern_c bool C__blas_dcopy(index_t * L1_u,index_t * L1_v)
{
TRACE_PUSH("C__blas_dcopy"); MM_ENTER;
{
{
int L2_0_n;
double * L_Tmp3;
double * L_Tmp4;
{
double L3_1_a;
double L3_2_b;
RTERR_DIM(0 < 0 || 0 >= 1);
L3_1_a = (int)((L1_u)->dim[0]);
RTERR_DIM(0 < 0 || 0 >= 1);
L3_2_b = (int)((L1_v)->dim[0]);
 if ((L3_1_a<L3_2_b)) { 
L2_0_n = L3_1_a;
 } else { 
L2_0_n = L3_2_b;
 } 
}
L_Tmp3 = IND_BASE_TYPED((L1_u),double );
L_Tmp4 = IND_BASE_TYPED((L1_v),double );
 dcopy_(&(L2_0_n), (L_Tmp3), (L1_u)->mod, (L_Tmp4), (L1_v)->mod);
}
TRACE_POP("C__blas_dcopy");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-ddot
 */
extern_c double C__blas_ddot(index_t * L1_u,index_t * L1_v)
{
TRACE_PUSH("C__blas_ddot"); MM_ENTER;
{
double L_Tmp0;
double * L_Tmp1;
double * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 1);
 if (((int)((L1_u)->dim[0])!=(int)((L1_v)->dim[0]))) { 
lush_error("vectors have different lengths");
 } 
L_Tmp1 = IND_BASE_TYPED((L1_u),double );
L_Tmp2 = IND_BASE_TYPED((L1_v),double );
L_Tmp0 = (double)( ddot_((L1_u)->dim,(L_Tmp1),(L1_u)->mod,(L_Tmp2),(L1_v)->mod));
TRACE_POP("C__blas_ddot");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION -blas-daxpy!
 */
extern_c bool C__blas_daxpyD(double L1_alpha,index_t * L1_u,index_t * L1_v)
{
TRACE_PUSH("C__blas_daxpyD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
L_Tmp0 = IND_BASE_TYPED((L1_u),double );
L_Tmp1 = IND_BASE_TYPED((L1_v),double );
 daxpy_((L1_v)->dim, &(L1_alpha), (L_Tmp0), (L1_u)->mod, (L_Tmp1), (L1_v)->mod);
TRACE_POP("C__blas_daxpyD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dnrm2
 */
extern_c double C__blas_dnrm2(index_t * L1_v)
{
TRACE_PUSH("C__blas_dnrm2"); MM_ENTER;
{
double L_Tmp0;
double * L_Tmp1;
L_Tmp1 = IND_BASE_TYPED((L1_v),double );
L_Tmp0 = (double)( dnrm2_((L1_v)->dim,(L_Tmp1),(L1_v)->mod));
TRACE_POP("C__blas_dnrm2");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION -blas-drotg!
 */
extern_c bool C__blas_drotgD(index_t * L1_abcs)
{
TRACE_PUSH("C__blas_drotgD"); MM_ENTER;
{
double * L_Tmp0;
RTERR_DIM(0 < 0 || 0 >= 1);
 if ((1!=(L1_abcs)->mod[0])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
 if (((int)((L1_abcs)->dim[0])<4)) { 
lush_error("input array too short");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_abcs),double );
{
  double *dp = (L_Tmp0);
  drotg_(dp, dp+1, dp+2, dp+3);
  }
TRACE_POP("C__blas_drotgD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-drotg
 */
extern_c index_t * C__blas_drotg(double L1_a,double L1_b)
{
TRACE_PUSH("C__blas_drotg"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(1);
storage_t *L2_0_srg = new_storage(ST_DOUBLE);
{
index_t * L2_1_cs;
(L2_0_array)->st = L2_0_srg;
Midx_init_dim1(L2_0_array, 4);
RTERR_DIM(L2_0_array->dim[0]<0);
Midx_maclear(L2_0_array, double );
L2_1_cs = L2_0_array;
RTERR_BOUND(0>=(L2_1_cs)->dim[0]);
IDX_PTR(L2_1_cs,double )[(L2_1_cs)->mod[0]*((int)0)] = L1_a;
RTERR_BOUND(1>=(L2_1_cs)->dim[0]);
IDX_PTR(L2_1_cs,double )[(L2_1_cs)->mod[0]*((int)1)] = L1_b;
C__blas_drotgD(L2_1_cs);
RTERR_GEN((((int)2)+((int)2) > ((int)(L2_1_cs)->dim[((int)0)])), "specified interval is too large");
Midx_narrow(L2_1_cs,((int)0),((int)2),((int)2),double );
L_Tmp0 = L2_1_cs;
}
TRACE_POP("C__blas_drotg");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION -blas-drot!
 */
extern_c bool C__blas_drotD(index_t * L1_x,index_t * L1_y,index_t * L1_cs)
{
TRACE_PUSH("C__blas_drotD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
double * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 1);
 if (((int)((L1_x)->dim[0])!=(int)((L1_y)->dim[0]))) { 
lush_error("x and y are of different length");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
 if (((int)((L1_cs)->dim[0])!=2)) { 
lush_error("<cs> is not a two-element vector");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_cs),double );
L_Tmp1 = IND_BASE_TYPED((L1_x),double );
L_Tmp2 = IND_BASE_TYPED((L1_y),double );
{
  double *cs = (L_Tmp0);
  drot_((L1_x)->dim,(L_Tmp1),(L1_x)->mod,(L_Tmp2),(L1_y)->mod,cs,cs+1);
  }
TRACE_POP("C__blas_drotD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dscal!
 */
extern_c bool C__blas_dscalD(double L1_alpha,index_t * L1_u)
{
TRACE_PUSH("C__blas_dscalD"); MM_ENTER;
{
double * L_Tmp0;
L_Tmp0 = IND_BASE_TYPED((L1_u),double );
 dscal_((L1_u)->dim,&(L1_alpha),(L_Tmp0),(L1_u)->mod);
TRACE_POP("C__blas_dscalD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dscal1!
 */
extern_c bool C__blas_dscal1D(index_t * L1_u)
{
TRACE_PUSH("C__blas_dscal1D"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
L_Tmp0 = IND_BASE_TYPED((L1_u),double );
L_Tmp1 = IND_BASE_TYPED((L1_u),double );
 
  double l = 1/dnrm2_((L1_u)->dim,(L_Tmp0),(L1_u)->mod);
  dscal_((L1_u)->dim,&l,(L_Tmp1),(L1_u)->mod);
TRACE_POP("C__blas_dscal1D");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dswap
 */
extern_c bool C__blas_dswap(index_t * L1_x,index_t * L1_y)
{
TRACE_PUSH("C__blas_dswap"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 1);
 if (((int)((L1_x)->dim[0])!=(int)((L1_y)->dim[0]))) { 
lush_error("x and y are of different length");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_x),double );
L_Tmp1 = IND_BASE_TYPED((L1_y),double );
 dswap_((L1_x)->dim,(L_Tmp0),(L1_x)->mod,(L_Tmp1),(L1_y)->mod);
TRACE_POP("C__blas_dswap");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dsum
 */
extern_c double C__blas_dsum(index_t * L1_u)
{
TRACE_PUSH("C__blas_dsum"); MM_ENTER;
{
double L_Tmp0;
double * L_Tmp1;
 const int incv = 0; const double v = 1;
L_Tmp1 = IND_BASE_TYPED((L1_u),double );
L_Tmp0 = (double)( ddot_((L1_u)->dim,(L_Tmp1),(L1_u)->mod, &v , &incv));
TRACE_POP("C__blas_dsum");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION -blas-dgemv!
 */
extern_c bool C__blas_dgemvD(double L1_alpha,index_t * L1_A,index_t * L1_x,double L1_beta,index_t * L1_y)
{
TRACE_PUSH("C__blas_dgemvD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
double * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((int)((L1_x)->dim[0])!=(L1_A)->dim[1])) { 
lush_error("u does not match row length of A");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((int)((L1_y)->dim[0])!=(L1_A)->dim[0])) { 
lush_error("v does not match column length of A");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_A),double );
L_Tmp1 = IND_BASE_TYPED((L1_x),double );
L_Tmp2 = IND_BASE_TYPED((L1_y),double );
 dgemv_("T",(L1_A)->dim+1,(L1_A)->dim,&(L1_alpha),(L_Tmp0),(L1_A)->mod,(L_Tmp1),(L1_x)->mod,&(L1_beta),(L_Tmp2),(L1_y)->mod);
TRACE_POP("C__blas_dgemvD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dgemv
 */
extern_c index_t * C__blas_dgemv(double L1_alpha,index_t * L1_A,index_t * L1_x)
{
TRACE_PUSH("C__blas_dgemv"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(1);
storage_t *L2_0_srg = new_storage(ST_DOUBLE);
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((int)((L1_x)->dim[0])!=(L1_A)->dim[1])) { 
lush_error("u does not match row length of A");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
{
index_t * L2_1_y;
double L2_2_beta;
double * L_Tmp3;
double * L_Tmp4;
double * L_Tmp5;
(L2_0_array)->st = L2_0_srg;
RTERR_DIM(0 < 0 || 0 >= 2);
Midx_init_dim1(L2_0_array, (L1_A)->dim[0]);
RTERR_DIM(L2_0_array->dim[0]<0);
L2_1_y = L2_0_array;
L2_2_beta = 0;
L_Tmp3 = IND_BASE_TYPED((L1_A),double );
L_Tmp4 = IND_BASE_TYPED((L1_x),double );
L_Tmp5 = IND_BASE_TYPED((L2_1_y),double );
 dgemv_("T",(L1_A)->dim+1,(L1_A)->dim,&(L1_alpha),(L_Tmp3),(L1_A)->mod,(L_Tmp4),(L1_x)->mod,&(L2_2_beta),(L_Tmp5),(L2_1_y)->mod);
L_Tmp0 = L2_1_y;
}
TRACE_POP("C__blas_dgemv");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION -blas-dgevm!
 */
extern_c bool C__blas_dgevmD(double L1_alpha,index_t * L1_x,index_t * L1_A,double L1_beta,index_t * L1_y)
{
TRACE_PUSH("C__blas_dgevmD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
double * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((int)((L1_x)->dim[0])!=(L1_A)->dim[0])) { 
lush_error("u does not match column length of A");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((int)((L1_y)->dim[0])!=(L1_A)->dim[1])) { 
lush_error("v does not match row length of A");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_A),double );
L_Tmp1 = IND_BASE_TYPED((L1_x),double );
L_Tmp2 = IND_BASE_TYPED((L1_y),double );
 dgemv_("N",(L1_A)->dim+1,(L1_A)->dim,&(L1_alpha),(L_Tmp0),(L1_A)->mod,(L_Tmp1),(L1_x)->mod,&(L1_beta),(L_Tmp2),(L1_y)->mod);
TRACE_POP("C__blas_dgevmD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dgevm
 */
extern_c index_t * C__blas_dgevm(double L1_alpha,index_t * L1_x,index_t * L1_A)
{
TRACE_PUSH("C__blas_dgevm"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(1);
storage_t *L2_0_srg = new_storage(ST_DOUBLE);
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((int)((L1_x)->dim[0])!=(L1_A)->dim[0])) { 
lush_error("u does not match column length of A");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
{
index_t * L2_1_y;
double L2_2_beta;
double * L_Tmp3;
double * L_Tmp4;
double * L_Tmp5;
(L2_0_array)->st = L2_0_srg;
RTERR_DIM(1 < 0 || 1 >= 2);
Midx_init_dim1(L2_0_array, (L1_A)->dim[1]);
RTERR_DIM(L2_0_array->dim[0]<0);
L2_1_y = L2_0_array;
L2_2_beta = 0;
L_Tmp3 = IND_BASE_TYPED((L1_A),double );
L_Tmp4 = IND_BASE_TYPED((L1_x),double );
L_Tmp5 = IND_BASE_TYPED((L2_1_y),double );
 dgemv_("N",(L1_A)->dim+1,(L1_A)->dim,&(L1_alpha),(L_Tmp3),(L1_A)->mod,(L_Tmp4),(L1_x)->mod,&(L2_2_beta),(L_Tmp5),(L2_1_y)->mod);
L_Tmp0 = L2_1_y;
}
TRACE_POP("C__blas_dgevm");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION -blas-dger1!
 */
extern_c bool C__blas_dger1D(double L1_alpha,index_t * L1_u,index_t * L1_v,index_t * L1_A)
{
TRACE_PUSH("C__blas_dger1D"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
double * L_Tmp2;
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((int)((L1_u)->dim[0])!=(L1_A)->dim[0])) { 
lush_error("u does not match column length of A");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((int)((L1_v)->dim[0])!=(L1_A)->dim[1])) { 
lush_error("v does not match row length of A");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_v),double );
L_Tmp1 = IND_BASE_TYPED((L1_u),double );
L_Tmp2 = IND_BASE_TYPED((L1_A),double );
 dger_((L1_A)->dim+1,(L1_A)->dim,&(L1_alpha),(L_Tmp0),(L1_v)->mod,(L_Tmp1),(L1_u)->mod,(L_Tmp2),(L1_A)->mod);
TRACE_POP("C__blas_dger1D");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dsymv!
 */
extern_c bool C__blas_dsymvD(double L1_alpha,index_t * L1_A,index_t * L1_x,double L1_beta,index_t * L1_y)
{
TRACE_PUSH("C__blas_dsymvD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
double * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((int)((L1_x)->dim[0])!=(L1_A)->dim[1])) { 
lush_error("u does not match row length of A");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((int)((L1_y)->dim[0])!=(L1_A)->dim[0])) { 
lush_error("v does not match column length of A");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_A),double );
L_Tmp1 = IND_BASE_TYPED((L1_x),double );
L_Tmp2 = IND_BASE_TYPED((L1_y),double );
 dsymv_("L",(L1_A)->dim,&(L1_alpha),(L_Tmp0),(L1_A)->mod,(L_Tmp1),(L1_x)->mod,&(L1_beta),(L_Tmp2),(L1_y)->mod);
TRACE_POP("C__blas_dsymvD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dsymv
 */
extern_c index_t * C__blas_dsymv(double L1_alpha,index_t * L1_A,index_t * L1_x)
{
TRACE_PUSH("C__blas_dsymv"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(1);
storage_t *L2_0_srg = new_storage(ST_DOUBLE);
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_A)->dim[0]==(L1_A)->dim[1]))) { 
lush_error("A not square");
 } 
RTERR_DIM(0 < 0 || 0 >= 1);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((int)((L1_x)->dim[0])!=(L1_A)->dim[1])) { 
lush_error("u does not match row length of A");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
{
index_t * L2_1_y;
double L2_2_beta;
double * L_Tmp3;
double * L_Tmp4;
double * L_Tmp5;
(L2_0_array)->st = L2_0_srg;
RTERR_DIM(0 < 0 || 0 >= 2);
Midx_init_dim1(L2_0_array, (L1_A)->dim[0]);
RTERR_DIM(L2_0_array->dim[0]<0);
L2_1_y = L2_0_array;
L2_2_beta = 0;
L_Tmp3 = IND_BASE_TYPED((L1_A),double );
L_Tmp4 = IND_BASE_TYPED((L1_x),double );
L_Tmp5 = IND_BASE_TYPED((L2_1_y),double );
 dsymv_("L",(L1_A)->dim,&(L1_alpha),(L_Tmp3),(L1_A)->mod,(L_Tmp4),(L1_x)->mod,&(L2_2_beta),(L_Tmp5),(L2_1_y)->mod);
L_Tmp0 = L2_1_y;
}
TRACE_POP("C__blas_dsymv");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION -blas-dutsv!
 */
extern_c bool C__blas_dutsvD(index_t * L1_U,index_t * L1_x)
{
TRACE_PUSH("C__blas_dutsvD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_U)->dim[0]==(L1_U)->dim[1]))) { 
lush_error("U not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(0 < 0 || 0 >= 1);
 if (((L1_U)->dim[1]!=(int)((L1_x)->dim[0]))) { 
lush_error("arguments invalid for matrix-vector multiply");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_U),double );
L_Tmp1 = IND_BASE_TYPED((L1_x),double );
 dtrsv_("L","T","N",(L1_U)->dim,(L_Tmp0),(L1_U)->mod,(L_Tmp1),(L1_x)->mod);
TRACE_POP("C__blas_dutsvD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dgemm!
 */
extern_c bool C__blas_dgemmD(double L1_alpha,index_t * L1_A,index_t * L1_B,double L1_beta,index_t * L1_C)
{
TRACE_PUSH("C__blas_dgemmD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
double * L_Tmp2;
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_A)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_C)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((L1_A)->dim[1]!=(L1_B)->dim[0])) { 
lush_error("matrices invalid for matrix-matrix multiply");
 } 
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((L1_A)->dim[0]!=(L1_C)->dim[0])) { 
lush_error("A and C not compatible");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (((L1_B)->dim[1]!=(L1_C)->dim[1])) { 
lush_error("B and C not compatible");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_B),double );
L_Tmp1 = IND_BASE_TYPED((L1_A),double );
L_Tmp2 = IND_BASE_TYPED((L1_C),double );
 dgemm_("N","N",(L1_C)->dim+1,(L1_C)->dim,(L1_B)->dim,&(L1_alpha),(L_Tmp0),(L1_B)->mod,(L_Tmp1),(L1_A)->mod,&(L1_beta),(L_Tmp2),(L1_C)->mod);
TRACE_POP("C__blas_dgemmD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dgemm
 */
extern_c index_t * C__blas_dgemm(double L1_alpha,index_t * L1_A,index_t * L1_B)
{
TRACE_PUSH("C__blas_dgemm"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(2);
storage_t *L2_0_srg = new_storage(ST_DOUBLE);
{
index_t * L2_1_C;
(L2_0_array)->st = L2_0_srg;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
Midx_init_dim2(L2_0_array, (L1_A)->dim[0],(L1_B)->dim[1]);
RTERR_DIM(L2_0_array->dim[0]<0);
RTERR_DIM(L2_0_array->dim[1]<0);
L2_1_C = L2_0_array;
C__blas_dgemmD(L1_alpha, L1_A, L1_B, 0, L2_1_C);
L_Tmp0 = L2_1_C;
}
TRACE_POP("C__blas_dgemm");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION -blas-dsymm!
 */
extern_c bool C__blas_dsymmD(double L1_alpha,index_t * L1_S,index_t * L1_B,double L1_beta,index_t * L1_C)
{
TRACE_PUSH("C__blas_dsymmD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
double * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_S)->dim[0]==(L1_S)->dim[1]))) { 
lush_error("S not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_S)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_S),double );
L_Tmp1 = IND_BASE_TYPED((L1_B),double );
L_Tmp2 = IND_BASE_TYPED((L1_C),double );
 dsymm_("R","L",(L1_C)->dim+1,(L1_C)->dim,&(L1_alpha),(L_Tmp0),(L1_S)->mod,(L_Tmp1),(L1_B)->mod,&(L1_beta),(L_Tmp2),(L1_C)->mod);
TRACE_POP("C__blas_dsymmD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dmsym!
 */
extern_c bool C__blas_dmsymD(double L1_alpha,index_t * L1_B,index_t * L1_S,double L1_beta,index_t * L1_C)
{
TRACE_PUSH("C__blas_dmsymD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
double * L_Tmp2;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_S)->dim[0]==(L1_S)->dim[1]))) { 
lush_error("S not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_S)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_S),double );
L_Tmp1 = IND_BASE_TYPED((L1_B),double );
L_Tmp2 = IND_BASE_TYPED((L1_C),double );
 dsymm_("L","L",(L1_C)->dim+1,(L1_C)->dim,&(L1_alpha),(L_Tmp0),(L1_S)->mod,(L_Tmp1),(L1_B)->mod,&(L1_beta),(L_Tmp2),(L1_C)->mod);
TRACE_POP("C__blas_dmsymD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dutmm!
 */
extern_c bool C__blas_dutmmD(double L1_alpha,index_t * L1_U,index_t * L1_B)
{
TRACE_PUSH("C__blas_dutmmD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_U)->dim[0]==(L1_U)->dim[1]))) { 
lush_error("U not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((L1_U)->dim[1]!=(L1_B)->dim[0])) { 
lush_error("matrices invalid for matrix-matrix multiply");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_U)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_U),double );
L_Tmp1 = IND_BASE_TYPED((L1_B),double );
 dtrmm_("R","L","N","N",(L1_B)->dim+1,(L1_B)->dim,&(L1_alpha),(L_Tmp0),(L1_U)->mod,(L_Tmp1),(L1_B)->mod);
TRACE_POP("C__blas_dutmmD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dmutm!
 */
extern_c bool C__blas_dmutmD(double L1_alpha,index_t * L1_B,index_t * L1_U)
{
TRACE_PUSH("C__blas_dmutmD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_U)->dim[0]==(L1_U)->dim[1]))) { 
lush_error("U not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((L1_B)->dim[1]!=(L1_U)->dim[0])) { 
lush_error("matrices invalid for matrix-matrix multiply");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_U)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_U),double );
L_Tmp1 = IND_BASE_TYPED((L1_B),double );
 dtrmm_("L","L","N","N",(L1_B)->dim+1,(L1_B)->dim,&(L1_alpha),(L_Tmp0),(L1_U)->mod,(L_Tmp1),(L1_B)->mod);
TRACE_POP("C__blas_dmutmD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dutsm!
 */
extern_c bool C__blas_dutsmD(double L1_alpha,index_t * L1_U,index_t * L1_B)
{
TRACE_PUSH("C__blas_dutsmD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_U)->dim[0]==(L1_U)->dim[1]))) { 
lush_error("U not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((L1_U)->dim[1]!=(L1_B)->dim[0])) { 
lush_error("matrices invalid for matrix-matrix multiply");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_U)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_U),double );
L_Tmp1 = IND_BASE_TYPED((L1_B),double );
 dtrsm_("R","L","N","N",(L1_B)->dim+1,(L1_B)->dim,&(L1_alpha),(L_Tmp0),(L1_U)->mod,(L_Tmp1),(L1_B)->mod);
TRACE_POP("C__blas_dutsmD");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION -blas-dmuts!
 */
extern_c bool C__blas_dmutsD(double L1_alpha,index_t * L1_B,index_t * L1_U)
{
TRACE_PUSH("C__blas_dmutsD"); MM_ENTER;
{
double * L_Tmp0;
double * L_Tmp1;
RTERR_DIM(0 < 0 || 0 >= 2);
RTERR_DIM(1 < 0 || 1 >= 2);
 if (!(((L1_U)->dim[0]==(L1_U)->dim[1]))) { 
lush_error("U not square");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
RTERR_DIM(0 < 0 || 0 >= 2);
 if (((L1_B)->dim[1]!=(L1_U)->dim[0])) { 
lush_error("matrices invalid for matrix-matrix multiply");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_U)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
RTERR_DIM(1 < 0 || 1 >= 2);
 if ((1!=(L1_B)->mod[1])) { 
lush_error("array must be contiguous in last dimension");
 } 
L_Tmp0 = IND_BASE_TYPED((L1_U),double );
L_Tmp1 = IND_BASE_TYPED((L1_B),double );
 dtrsm_("L","L","N","N",(L1_B)->dim+1,(L1_B)->dim,&(L1_alpha),(L_Tmp0),(L1_U)->mod,(L_Tmp1),(L1_B)->mod);
TRACE_POP("C__blas_dmutsD");
MM_EXIT; return 0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB -blas-dasum
 */
DH(X__blas_dasum)
{
dharg ret;
ret.dh_double =  C__blas_dasum(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dasum
 */
DHDOC(K__blas_dasum_Rf954c1ec,X__blas_dasum,"C__blas_dasum",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_DOUBLE,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-diamax
 */
DH(X__blas_diamax)
{
dharg ret;
ret.dh_double =  C__blas_diamax(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-diamax
 */
DHDOC(K__blas_diamax_Rf954c1ec,X__blas_diamax,"C__blas_diamax",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_DOUBLE,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dclr!
 */
DH(X__blas_dclrD)
{
dharg ret;
ret.dh_bool =  C__blas_dclrD(a[1].dh_double, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dclr!
 */
DHDOC(K__blas_dclrD_R4eb72a7f,X__blas_dclrD,"C__blas_dclrD",0,0) = {
DH_FUNC(2),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dcopy
 */
DH(X__blas_dcopy)
{
dharg ret;
ret.dh_bool =  C__blas_dcopy(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dcopy
 */
DHDOC(K__blas_dcopy_R450167d5,X__blas_dcopy,"C__blas_dcopy",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-ddot
 */
DH(X__blas_ddot)
{
dharg ret;
ret.dh_double =  C__blas_ddot(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-ddot
 */
DHDOC(K__blas_ddot_R4f8ae150,X__blas_ddot,"C__blas_ddot",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_DOUBLE,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-daxpy!
 */
DH(X__blas_daxpyD)
{
dharg ret;
ret.dh_bool =  C__blas_daxpyD(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-daxpy!
 */
DHDOC(K__blas_daxpyD_R3fd1bdf8,X__blas_daxpyD,"C__blas_daxpyD",0,0) = {
DH_FUNC(3),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dnrm2
 */
DH(X__blas_dnrm2)
{
dharg ret;
ret.dh_double =  C__blas_dnrm2(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dnrm2
 */
DHDOC(K__blas_dnrm2_Rf954c1ec,X__blas_dnrm2,"C__blas_dnrm2",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_DOUBLE,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-drotg!
 */
DH(X__blas_drotgD)
{
dharg ret;
ret.dh_bool =  C__blas_drotgD(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-drotg!
 */
DHDOC(K__blas_drotgD_Rf3df4769,X__blas_drotgD,"C__blas_drotgD",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-drotg
 */
DH(X__blas_drotg)
{
dharg ret;
ret.dh_idx_ptr =  C__blas_drotg(a[1].dh_double, a[2].dh_double);
return ret;
}

/*
 * DHDOC -blas-drotg
 */
DHDOC(K__blas_drotg_Re15ceef5,X__blas_drotg,"C__blas_drotg",0,0) = {
DH_FUNC(2),
DH_DOUBLE,
DH_DOUBLE,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_WRITE),
DH_DOUBLE,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-drot!
 */
DH(X__blas_drotD)
{
dharg ret;
ret.dh_bool =  C__blas_drotD(a[1].dh_idx_ptr, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-drot!
 */
DHDOC(K__blas_drotD_R28bd26ac,X__blas_drotD,"C__blas_drotD",0,0) = {
DH_FUNC(3),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dscal!
 */
DH(X__blas_dscalD)
{
dharg ret;
ret.dh_bool =  C__blas_dscalD(a[1].dh_double, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dscal!
 */
DHDOC(K__blas_dscalD_R4eb72a7f,X__blas_dscalD,"C__blas_dscalD",0,0) = {
DH_FUNC(2),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dscal1!
 */
DH(X__blas_dscal1D)
{
dharg ret;
ret.dh_bool =  C__blas_dscal1D(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dscal1!
 */
DHDOC(K__blas_dscal1D_Rf3df4769,X__blas_dscal1D,"C__blas_dscal1D",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dswap
 */
DH(X__blas_dswap)
{
dharg ret;
ret.dh_bool =  C__blas_dswap(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dswap
 */
DHDOC(K__blas_dswap_R450167d5,X__blas_dswap,"C__blas_dswap",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dsum
 */
DH(X__blas_dsum)
{
dharg ret;
ret.dh_double =  C__blas_dsum(a[1].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dsum
 */
DHDOC(K__blas_dsum_Rf954c1ec,X__blas_dsum,"C__blas_dsum",0,0) = {
DH_FUNC(1),
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_DOUBLE,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dgemv!
 */
DH(X__blas_dgemvD)
{
dharg ret;
ret.dh_bool =  C__blas_dgemvD(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_double, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dgemv!
 */
DHDOC(K__blas_dgemvD_R13308141,X__blas_dgemvD,"C__blas_dgemvD",0,0) = {
DH_FUNC(5),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dgemv
 */
DH(X__blas_dgemv)
{
dharg ret;
ret.dh_idx_ptr =  C__blas_dgemv(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dgemv
 */
DHDOC(K__blas_dgemv_R95e15fa7,X__blas_dgemv,"C__blas_dgemv",0,0) = {
DH_FUNC(3),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dgevm!
 */
DH(X__blas_dgevmD)
{
dharg ret;
ret.dh_bool =  C__blas_dgevmD(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_double, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dgevm!
 */
DHDOC(K__blas_dgevmD_R13308141,X__blas_dgevmD,"C__blas_dgevmD",0,0) = {
DH_FUNC(5),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dgevm
 */
DH(X__blas_dgevm)
{
dharg ret;
ret.dh_idx_ptr =  C__blas_dgevm(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dgevm
 */
DHDOC(K__blas_dgevm_R95e15fa7,X__blas_dgevm,"C__blas_dgevm",0,0) = {
DH_FUNC(3),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dger1!
 */
DH(X__blas_dger1D)
{
dharg ret;
ret.dh_bool =  C__blas_dger1D(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dger1!
 */
DHDOC(K__blas_dger1D_Rdd1c92f6,X__blas_dger1D,"C__blas_dger1D",0,0) = {
DH_FUNC(4),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dsymv!
 */
DH(X__blas_dsymvD)
{
dharg ret;
ret.dh_bool =  C__blas_dsymvD(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_double, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dsymv!
 */
DHDOC(K__blas_dsymvD_R13308141,X__blas_dsymvD,"C__blas_dsymvD",0,0) = {
DH_FUNC(5),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dsymv
 */
DH(X__blas_dsymv)
{
dharg ret;
ret.dh_idx_ptr =  C__blas_dsymv(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dsymv
 */
DHDOC(K__blas_dsymv_R95e15fa7,X__blas_dsymv,"C__blas_dsymv",0,0) = {
DH_FUNC(3),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dutsv!
 */
DH(X__blas_dutsvD)
{
dharg ret;
ret.dh_bool =  C__blas_dutsvD(a[1].dh_idx_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dutsv!
 */
DHDOC(K__blas_dutsvD_R450167d5,X__blas_dutsvD,"C__blas_dutsvD",0,0) = {
DH_FUNC(2),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,1),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dgemm!
 */
DH(X__blas_dgemmD)
{
dharg ret;
ret.dh_bool =  C__blas_dgemmD(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_double, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dgemm!
 */
DHDOC(K__blas_dgemmD_R13308141,X__blas_dgemmD,"C__blas_dgemmD",0,0) = {
DH_FUNC(5),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dgemm
 */
DH(X__blas_dgemm)
{
dharg ret;
ret.dh_idx_ptr =  C__blas_dgemm(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dgemm
 */
DHDOC(K__blas_dgemm_R95e15fa7,X__blas_dgemm,"C__blas_dgemm",0,0) = {
DH_FUNC(3),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dsymm!
 */
DH(X__blas_dsymmD)
{
dharg ret;
ret.dh_bool =  C__blas_dsymmD(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_double, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dsymm!
 */
DHDOC(K__blas_dsymmD_R13308141,X__blas_dsymmD,"C__blas_dsymmD",0,0) = {
DH_FUNC(5),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dmsym!
 */
DH(X__blas_dmsymD)
{
dharg ret;
ret.dh_bool =  C__blas_dmsymD(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr, a[4].dh_double, a[5].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dmsym!
 */
DHDOC(K__blas_dmsymD_R13308141,X__blas_dmsymD,"C__blas_dmsymD",0,0) = {
DH_FUNC(5),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dutmm!
 */
DH(X__blas_dutmmD)
{
dharg ret;
ret.dh_bool =  C__blas_dutmmD(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dutmm!
 */
DHDOC(K__blas_dutmmD_R3fd1bdf8,X__blas_dutmmD,"C__blas_dutmmD",0,0) = {
DH_FUNC(3),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dmutm!
 */
DH(X__blas_dmutmD)
{
dharg ret;
ret.dh_bool =  C__blas_dmutmD(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dmutm!
 */
DHDOC(K__blas_dmutmD_R3fd1bdf8,X__blas_dmutmD,"C__blas_dmutmD",0,0) = {
DH_FUNC(3),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dutsm!
 */
DH(X__blas_dutsmD)
{
dharg ret;
ret.dh_bool =  C__blas_dutsmD(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dutsm!
 */
DHDOC(K__blas_dutsmD_R3fd1bdf8,X__blas_dutsmD,"C__blas_dutsmD",0,0) = {
DH_FUNC(3),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB -blas-dmuts!
 */
DH(X__blas_dmutsD)
{
dharg ret;
ret.dh_bool =  C__blas_dmutsD(a[1].dh_double, a[2].dh_idx_ptr, a[3].dh_idx_ptr);
return ret;
}

/*
 * DHDOC -blas-dmuts!
 */
DHDOC(K__blas_dmutsD_R3fd1bdf8,X__blas_dmutsD,"C__blas_dmutsD",0,0) = {
DH_FUNC(3),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_DOUBLE,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_blas_double(void)
{
 dh_define("-blas-dasum", &K__blas_dasum_Rf954c1ec); 
 dh_define("-blas-diamax", &K__blas_diamax_Rf954c1ec); 
 dh_define("-blas-dclr!", &K__blas_dclrD_R4eb72a7f); 
 dh_define("-blas-dcopy", &K__blas_dcopy_R450167d5); 
 dh_define("-blas-ddot", &K__blas_ddot_R4f8ae150); 
 dh_define("-blas-daxpy!", &K__blas_daxpyD_R3fd1bdf8); 
 dh_define("-blas-dnrm2", &K__blas_dnrm2_Rf954c1ec); 
 dh_define("-blas-drotg!", &K__blas_drotgD_Rf3df4769); 
 dh_define("-blas-drotg", &K__blas_drotg_Re15ceef5); 
 dh_define("-blas-drot!", &K__blas_drotD_R28bd26ac); 
 dh_define("-blas-dscal!", &K__blas_dscalD_R4eb72a7f); 
 dh_define("-blas-dscal1!", &K__blas_dscal1D_Rf3df4769); 
 dh_define("-blas-dswap", &K__blas_dswap_R450167d5); 
 dh_define("-blas-dsum", &K__blas_dsum_Rf954c1ec); 
 dh_define("-blas-dgemv!", &K__blas_dgemvD_R13308141); 
 dh_define("-blas-dgemv", &K__blas_dgemv_R95e15fa7); 
 dh_define("-blas-dgevm!", &K__blas_dgevmD_R13308141); 
 dh_define("-blas-dgevm", &K__blas_dgevm_R95e15fa7); 
 dh_define("-blas-dger1!", &K__blas_dger1D_Rdd1c92f6); 
 dh_define("-blas-dsymv!", &K__blas_dsymvD_R13308141); 
 dh_define("-blas-dsymv", &K__blas_dsymv_R95e15fa7); 
 dh_define("-blas-dutsv!", &K__blas_dutsvD_R450167d5); 
 dh_define("-blas-dgemm!", &K__blas_dgemmD_R13308141); 
 dh_define("-blas-dgemm", &K__blas_dgemm_R95e15fa7); 
 dh_define("-blas-dsymm!", &K__blas_dsymmD_R13308141); 
 dh_define("-blas-dmsym!", &K__blas_dmsymD_R13308141); 
 dh_define("-blas-dutmm!", &K__blas_dutmmD_R3fd1bdf8); 
 dh_define("-blas-dmutm!", &K__blas_dmutmD_R3fd1bdf8); 
 dh_define("-blas-dutsm!", &K__blas_dutsmD_R3fd1bdf8); 
 dh_define("-blas-dmuts!", &K__blas_dmutsD_R3fd1bdf8); 
}

int majver_blas_double = 50;
int minver_blas_double = 01;


#endif

