/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"
#undef uchar



/* ---------------------------------------- */


/*
 * FUNCTION add-to-integer
 */
extern_c int C_add_to_integer(int L1_intg,int L1_arg)
{
TRACE_PUSH("C_add_to_integer"); MM_ENTER;
{
int L_Tmp0;
 (L1_intg) += (L1_arg);
L_Tmp0 = L1_intg;
TRACE_POP("C_add_to_integer");
MM_EXIT; return L_Tmp0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB add-to-integer
 */
DH(X_add_to_integer)
{
dharg ret;
ret.dh_int =  C_add_to_integer(a[1].dh_int, a[2].dh_int);
return ret;
}

/*
 * DHDOC add-to-integer
 */
DHDOC(K_add_to_integer_Re3bb2f24,X_add_to_integer,"C_add_to_integer",0,0) = {
DH_FUNC(2),
DH_INT,
DH_INT,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_add_to_integer(void)
{
 dh_define("add-to-integer", &K_add_to_integer_Re3bb2f24); 
}

int majver_add_to_integer = 50;
int minver_add_to_integer = 01;


#endif

