/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"
#undef uchar



/* ---------------------------------------- */


/*
 * FUNCTION ids
 */
extern_c char* C_ids(char* L1_s)
{
TRACE_PUSH("C_ids"); MM_ENTER;
{
char* L_Tmp0;
{
char* L2_1_o;
char *L2_0_str;
Mstr_alloc(L2_0_str, 0+1);
strcpy((char*)(L2_0_str),"");
L2_1_o = L2_0_str;
 (L2_1_o)=(L1_s);
L_Tmp0 = L2_1_o;
}
TRACE_POP("C_ids");
MM_EXIT; return L_Tmp0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB ids
 */
DH(X_ids)
{
dharg ret;
ret.dh_str_ptr =  C_ids(a[1].dh_str_ptr);
return ret;
}

/*
 * DHDOC ids
 */
DHDOC(K_ids_R5937a536,X_ids,"C_ids",0,0) = {
DH_FUNC(1),
DH_STR,
DH_RETURN,
DH_STR,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_ids(void)
{
 dh_define("ids", &K_ids_R5937a536); 
}

int majver_ids = 50;
int minver_ids = 01;


#endif

