/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"
#undef uchar



/* ---------------------------------------- */


/*
 * FUNCTION isNull
 */
extern_c bool C_isNull(gptr L1_p)
{
TRACE_PUSH("C_isNull"); MM_ENTER;
{
bool L_Tmp0;
L_Tmp0 = (bool)( ((L1_p) == 0));
TRACE_POP("C_isNull");
MM_EXIT; return L_Tmp0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB isNull
 */
DH(X_isNull)
{
dharg ret;
ret.dh_bool =  C_isNull(a[1].dh_gptr);
return ret;
}

/*
 * DHDOC isNull
 */
DHDOC(K_isNull_Rc7df00c0,X_isNull,"C_isNull",0,0) = {
DH_FUNC(1),
DH_GPTR(0),
DH_RETURN,
DH_BOOL,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_isNull(void)
{
 dh_define("isNull", &K_isNull_Rc7df00c0); 
}

int majver_isNull = 50;
int minver_isNull = 01;


#endif

