/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * USER DEFINED HEADERS
 */
#include <libpq-fe.h>
/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"
#undef uchar



/* ---------------------------------------- */


/*
 * FUNCTION pgsql-headers
 */
extern_c bool C_pgsql_headers()
{
TRACE_PUSH("C_pgsql_headers"); MM_ENTER;
{
TRACE_POP("C_pgsql_headers");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION pgsql-is-null
 */
extern_c bool C_pgsql_is_null(gptr L1_p)
{
TRACE_PUSH("C_pgsql_is_null"); MM_ENTER;
{
bool L_Tmp0;
L_Tmp0 = (bool)( ((L1_p) == 0));
TRACE_POP("C_pgsql_is_null");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION pgsql-connectdb
 */
extern_c PGconn * C_pgsql_connectdb(char* L1_connstr)
{
TRACE_PUSH("C_pgsql_connectdb"); MM_ENTER;
{
PGconn * L_Tmp0;
{
PGconn * L2_1_pgconn;
bool L_Tmp2;
L2_1_pgconn = (gptr)(0);
 (L2_1_pgconn) = PQconnectdb((const char *)(L1_connstr));
L_Tmp2 = (bool ) C_pgsql_is_null(L2_1_pgconn);
 if (L_Tmp2) { 
char *L2_0_str;
Mstr_alloc(L2_0_str, 23+1);
strcpy((char*)(L2_0_str),"Error connecting to DB:");
char *L2_1_str;
Mstr_alloc(L2_1_str, 
strlen((char*)(L2_0_str))+
strlen((char*)(L1_connstr))+
1);
strcpy((char*)(L2_1_str),(char*)(L2_0_str));
strcat((char*)(L2_1_str),(char*)(L1_connstr));
lush_error(L2_1_str);
 } 
L_Tmp0 = L2_1_pgconn;
}
TRACE_POP("C_pgsql_connectdb");
MM_EXIT; return L_Tmp0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB pgsql-headers
 */
DH(X_pgsql_headers)
{
dharg ret;
ret.dh_bool =  C_pgsql_headers();
return ret;
}

/*
 * DHDOC pgsql-headers
 */
DHDOC(K_pgsql_headers_Ra8b05737,X_pgsql_headers,"C_pgsql_headers",0,0) = {
DH_FUNC(0),
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB pgsql-is-null
 */
DH(X_pgsql_is_null)
{
dharg ret;
ret.dh_bool =  C_pgsql_is_null(a[1].dh_gptr);
return ret;
}

/*
 * DHDOC pgsql-is-null
 */
DHDOC(K_pgsql_is_null_Rc7df00c0,X_pgsql_is_null,"C_pgsql_is_null",0,0) = {
DH_FUNC(1),
DH_GPTR(0),
DH_RETURN,
DH_BOOL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB pgsql-connectdb
 */
DH(X_pgsql_connectdb)
{
dharg ret;
ret.dh_gptr =  C_pgsql_connectdb(a[1].dh_str_ptr);
return ret;
}

/*
 * DHDOC pgsql-connectdb
 */
DHDOC(K_pgsql_connectdb_R7fafadc3,X_pgsql_connectdb,"C_pgsql_connectdb",0,0) = {
DH_FUNC(1),
DH_STR,
DH_RETURN,
DH_GPTR("PGconn *"),
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_pgsql(void)
{
 dh_define("pgsql-headers", &K_pgsql_headers_Ra8b05737); 
 dh_define("pgsql-is-null", &K_pgsql_is_null_Rc7df00c0); 
 dh_define("pgsql-connectdb", &K_pgsql_connectdb_R7fafadc3); 
}

int majver_pgsql = 50;
int minver_pgsql = 01;


#endif

