/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"
#undef uchar



/* ---------------------------------------- */


/*
 * FUNCTION square
 */
extern_c int C_square(int L1_x)
{
TRACE_PUSH("C_square"); MM_ENTER;
{
int L_Tmp0;
L_Tmp0 = (L1_x*L1_x);
TRACE_POP("C_square");
MM_EXIT; return L_Tmp0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP


/*
 * STUB square
 */
DH(X_square)
{
dharg ret;
ret.dh_int =  C_square(a[1].dh_int);
return ret;
}

/*
 * DHDOC square
 */
DHDOC(K_square_R5d694478,X_square,"C_square",0,0) = {
DH_FUNC(1),
DH_INT,
DH_RETURN,
DH_INT,
DH_END_FUNC,
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_sq(void)
{
 dh_define("square", &K_square_R5d694478); 
}

int majver_sq = 50;
int minver_sq = 01;


#endif

