/* WARNING: Automatically generated code.
 * This code has been generated by the DH compiler.
 */
#ifdef HAVE_CONFIG_H
# include "lushconf.h"
#endif

/*
 * USER DEFINED HEADERS
 */
#include <sys/types.h>
#include <sys/mman.h>
#include <stdio.h>

/*
 * LUSH HEADERS
 */
#include "header.h"
#include "dh.h"
#include "idxmac.h"
#include "idxops.h"
#include "check_func.h"
#undef uchar

/*
 * DECLARATIONS
 */
extern_c bool  C_rewind ( FILE *  );
extern_c char*  C_fscan_str ( FILE *  );
extern_c bool  C_fclose ( FILE *  );
extern_c bool  C_skip_comments ( unsigned char , FILE *  );
extern_c bool  C_idx_u3resize ( index_t * , int , int , int  );
extern_c bool  C_idx_u2resize ( index_t * , int , int  );
extern_c int  C_fscan_int ( FILE *  );
extern_c int  C_fgetc ( FILE *  );
extern_c gptr  C_fopen ( char* , char*  );


/* ---------------------------------------- */


/*
 * FUNCTION pnm-dummy
 */
extern_c bool C_pnm_dummy()
{
TRACE_PUSH("C_pnm_dummy"); MM_ENTER;
{
TRACE_POP("C_pnm_dummy");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION pnm-header
 */
extern_c char* C_pnm_header(FILE * L1_f)
{
TRACE_PUSH("C_pnm_header"); MM_ENTER;
{
char* L_Tmp0;
 if (!(L1_f)) { 
lush_error("couldn't open PNM file");
 } 
C_rewind(L1_f);
{
char* L2_1_head;
bool L_Tmp2;
L2_1_head = (char* ) C_fscan_str(L1_f);
char *L2_0_str;
Mstr_alloc(L2_0_str, 2+1);
strcpy((char*)(L2_0_str),"P6");
 if ((strcmp((L2_0_str), (L2_1_head)) != 0)) { 
char *L2_1_str;
Mstr_alloc(L2_1_str, 2+1);
strcpy((char*)(L2_1_str),"P4");
 if ((strcmp((L2_1_str), (L2_1_head)) != 0)) { 
char *L2_2_str;
Mstr_alloc(L2_2_str, 2+1);
strcpy((char*)(L2_2_str),"P5");
 if ((strcmp((L2_2_str), (L2_1_head)) != 0)) { 
L_Tmp2 = true;
 } else { 
L_Tmp2 = 0;
 } 
 } else { 
L_Tmp2 = 0;
 } 
 } else { 
L_Tmp2 = 0;
 } 
 if (L_Tmp2) { 
C_fclose(L1_f);
 fprintf(stderr, "%s\n", (char *)((L2_1_head)));
lush_error(" not a valid binary PNM file");
 } 
C_skip_comments(35, L1_f);
L_Tmp0 = L2_1_head;
}
TRACE_POP("C_pnm_header");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION mmap-idx3-storage
 */
extern_c bool C_mmap_idx3_storage(FILE * L1_f,index_t * L1_u,int L1_d0,int L1_d1,int L1_d2)
{
TRACE_PUSH("C_mmap_idx3_storage"); MM_ENTER;
{
bool L_Tmp0;
{
bool L2_1_ok;
L2_1_ok = true;
{
    FILE *f=(FILE *) (L1_f);
    int size=(L1_d0) * (L1_d1) * (L1_d2);
    int offset=ftell(f);
    rewind(f);
    (L1_u)->st->size=size;
    (L1_u)->st->data=mmap(0,size+offset, PROT_READ,MAP_SHARED,fileno(f),0);
    if ((L1_u)->st->data == MAP_FAILED) (L2_1_ok)=0;
    (L1_u)->st->data = (char*)(L1_u)->st->data + offset;
    (L1_u)->st->kind = STS_MMAP;
    (L1_u)->st->isreadonly = true;
    }
 if (L2_1_ok) { 
C_idx_u3resize(L1_u, L1_d0, L1_d1, L1_d2);
 } 
L_Tmp0 = L2_1_ok;
}
TRACE_POP("C_mmap_idx3_storage");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION mmap-idx2-storage
 */
extern_c bool C_mmap_idx2_storage(FILE * L1_f,index_t * L1_u,int L1_d0,int L1_d1)
{
TRACE_PUSH("C_mmap_idx2_storage"); MM_ENTER;
{
bool L_Tmp0;
{
bool L2_1_ok;
L2_1_ok = true;
{
    FILE *f=(FILE *) (L1_f);
    int size=(L1_d0) * (L1_d1);
    int offset=ftell(f);
    rewind(f);
    (L1_u)->st->size=size;
    (L1_u)->st->data=mmap(0,size+offset, PROT_READ,MAP_SHARED,fileno(f),0);
    if ((L1_u)->st->data == MAP_FAILED) (L2_1_ok)=0;
    (L1_u)->st->data = (char*)(L1_u)->st->data + offset;
    (L1_u)->st->kind = STS_MMAP;
    (L1_u)->st->isreadonly = true;
    }
 if (L2_1_ok) { 
C_idx_u2resize(L1_u, L1_d0, L1_d1);
 } 
L_Tmp0 = L2_1_ok;
}
TRACE_POP("C_mmap_idx2_storage");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION pnm-fread-into-rgbx
 */
extern_c bool C_pnm_fread_into_rgbx(FILE * L1_f,index_t * L1_out)
{
TRACE_PUSH("C_pnm_fread_into_rgbx"); MM_ENTER;
{
{
char* L2_0_head;
int L2_1_nlino;
int L2_2_ncolo;
int L2_3_ncmpo;
L2_0_head = (char* ) C_pnm_header(L1_f);
RTERR_DIM(0 < 0 || 0 >= 3);
L2_1_nlino = (L1_out)->dim[0];
RTERR_DIM(1 < 0 || 1 >= 3);
L2_2_ncolo = (L1_out)->dim[1];
RTERR_DIM(2 < 0 || 2 >= 3);
L2_3_ncmpo = (L1_out)->dim[2];
char *L2_0_str;
Mstr_alloc(L2_0_str, 2+1);
strcpy((char*)(L2_0_str),"P4");
 if ((strcmp((L2_0_head), (L2_0_str)) == 0)) { 
{
int L3_4_ncol;
int L3_5_nlin;
int L3_6_n;
int L3_7_c;
bool L_Tmp8;
int L_Tmp9;
L3_4_ncol = (int ) C_fscan_int(L1_f);
L3_5_nlin = (int ) C_fscan_int(L1_f);
L3_6_n = 0;
L3_7_c = 0;
 if ((L3_4_ncol!=L2_2_ncolo)) { 
L_Tmp8 = true;
 } else { 
 if ((L3_5_nlin!=L2_1_nlino)) { 
L_Tmp8 = true;
 } else { 
 if ((L2_3_ncmpo<3)) { 
L_Tmp8 = true;
 } else { 
L_Tmp8 = 0;
 } 
 } 
 } 
 if (L_Tmp8) { 
{
double L4_10_b;
L4_10_b = 3;
 if ((L2_3_ncmpo>L4_10_b)) { 
L_Tmp9 = L2_3_ncmpo;
 } else { 
L_Tmp9 = L4_10_b;
 } 
}
C_idx_u3resize(L1_out, L3_5_nlin, L3_4_ncol, L_Tmp9);
 } 
C_fgetc(L1_f);
{ register unsigned char *_idx2loopc, *p;
  register int i, _imax = (L1_out)->dim[0];
  register int j, _jmax = (L1_out)->dim[1];
  register int _imat1_m0 = (L1_out)->mod[0];
  register int _imat1_m1 = (L1_out)->mod[1];
    _idx2loopc = IDX_PTR((L1_out),unsigned char);
  for (i=0; i <_imax; i++){;
    p= _idx2loopc;
    for (j=0; j <_jmax; j++){;
{ unsigned char v;
                if ((j == 0) || ((L3_6_n) == 0)) { (L3_7_c) = getc((FILE *)(L1_f)); (L3_6_n)=0; }
                v = ((L3_7_c) & 128) ? 0 : 255 ;
                p[0]= p[1]= p[2]= v ;  
                (L3_6_n) = ((L3_6_n) == 7) ? 0 : (L3_6_n)+1 ;
                (L3_7_c) = (L3_7_c) << 1; 
	     }
    p += _imat1_m1;
    }
     _idx2loopc += _imat1_m0;
  } }
}
 } else { 
char *L2_1_str;
Mstr_alloc(L2_1_str, 2+1);
strcpy((char*)(L2_1_str),"P5");
 if ((strcmp((L2_0_head), (L2_1_str)) == 0)) { 
{
int L3_11_ncol;
int L3_12_nlin;
bool L_Tmp13;
int L_Tmp14;
L3_11_ncol = (int ) C_fscan_int(L1_f);
L3_12_nlin = (int ) C_fscan_int(L1_f);
 if ((L3_11_ncol!=L2_2_ncolo)) { 
L_Tmp13 = true;
 } else { 
 if ((L3_12_nlin!=L2_1_nlino)) { 
L_Tmp13 = true;
 } else { 
 if ((L2_3_ncmpo<3)) { 
L_Tmp13 = true;
 } else { 
L_Tmp13 = 0;
 } 
 } 
 } 
 if (L_Tmp13) { 
{
double L4_15_b;
L4_15_b = 3;
 if ((L2_3_ncmpo>L4_15_b)) { 
L_Tmp14 = L2_3_ncmpo;
 } else { 
L_Tmp14 = L4_15_b;
 } 
}
C_idx_u3resize(L1_out, L3_12_nlin, L3_11_ncol, L_Tmp14);
 } 
C_fscan_int(L1_f);
C_fgetc(L1_f);
{ register unsigned char *_idx2loopc, *p;
  register int i, _imax = (L1_out)->dim[0];
  register int j, _jmax = (L1_out)->dim[1];
  register int _imat1_m0 = (L1_out)->mod[0];
  register int _imat1_m1 = (L1_out)->mod[1];
    _idx2loopc = IDX_PTR((L1_out),unsigned char);
  for (i=0; i <_imax; i++){;
    p= _idx2loopc;
    for (j=0; j <_jmax; j++){;
 p[0]=p[1]=p[2]=getc((FILE *)(L1_f));
    p += _imat1_m1;
    }
     _idx2loopc += _imat1_m0;
  } }
}
 } else { 
char *L2_2_str;
Mstr_alloc(L2_2_str, 2+1);
strcpy((char*)(L2_2_str),"P6");
 if ((strcmp((L2_0_head), (L2_2_str)) == 0)) { 
{
int L3_16_ncol;
int L3_17_nlin;
int L3_18_size;
bool L_Tmp19;
int L_Tmp20;
bool L_Tmp22;
bool L_Tmp23_contigue;
L3_16_ncol = (int ) C_fscan_int(L1_f);
L3_17_nlin = (int ) C_fscan_int(L1_f);
L3_18_size = (L3_17_nlin*L3_16_ncol);
 if ((L3_16_ncol!=L2_2_ncolo)) { 
L_Tmp19 = true;
 } else { 
 if ((L3_17_nlin!=L2_1_nlino)) { 
L_Tmp19 = true;
 } else { 
 if ((L2_3_ncmpo<3)) { 
L_Tmp19 = true;
 } else { 
L_Tmp19 = 0;
 } 
 } 
 } 
 if (L_Tmp19) { 
{
double L4_21_b;
L4_21_b = 3;
 if ((L2_3_ncmpo>L4_21_b)) { 
L_Tmp20 = L2_3_ncmpo;
 } else { 
L_Tmp20 = L4_21_b;
 } 
}
C_idx_u3resize(L1_out, L3_17_nlin, L3_16_ncol, L_Tmp20);
 } 
C_fscan_int(L1_f);
C_fgetc(L1_f);
RTERR_DIM(2 < 0 || 2 >= 3);
 if ((3==(L1_out)->dim[2])) { 
Midx_contiguep3(L1_out,L_Tmp23_contigue);
 if (L_Tmp23_contigue) { 
L_Tmp22 = true;
 } else { 
L_Tmp22 = 0;
 } 
 } else { 
L_Tmp22 = 0;
 } 
 if (L_Tmp22) { 
 if ((L3_18_size) != fread (IDX_PTR((L1_out), unsigned char), 3, (size_t) (L3_18_size), (FILE *)(L1_f)))
	              run_time_error("not enough items read");
 } else { 
{ register unsigned char *_idx2loopc, *p;
  register int i, _imax = (L1_out)->dim[0];
  register int j, _jmax = (L1_out)->dim[1];
  register int _imat1_m0 = (L1_out)->mod[0];
  register int _imat1_m1 = (L1_out)->mod[1];
    _idx2loopc = IDX_PTR((L1_out),unsigned char);
  for (i=0; i <_imax; i++){;
    p= _idx2loopc;
    for (j=0; j <_jmax; j++){;
 p[0]=getc((FILE *)(L1_f)) ;
  	         p[1]=getc((FILE *)(L1_f)) ;
	         p[2]=getc((FILE *)(L1_f)) ;
    p += _imat1_m1;
    }
     _idx2loopc += _imat1_m0;
  } }
 } 
}
 } else { 
 } 
 } 
 } 
}
TRACE_POP("C_pnm_fread_into_rgbx");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION pnm-read-into-rgbx
 */
extern_c bool C_pnm_read_into_rgbx(char* L1_s,index_t * L1_out)
{
TRACE_PUSH("C_pnm_read_into_rgbx"); MM_ENTER;
{
{
FILE * L2_0_f;
char *L2_0_str;
Mstr_alloc(L2_0_str, 2+1);
strcpy((char*)(L2_0_str),"rb");
L2_0_f = (gptr ) C_fopen(L1_s, L2_0_str);
 if (!(L2_0_f)) { 
lush_error("couldn't open PNM file");
 } 
C_pnm_fread_into_rgbx(L2_0_f, L1_out);
C_fclose(L2_0_f);
}
TRACE_POP("C_pnm_read_into_rgbx");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION pnm-fread-rgb
 */
extern_c index_t * C_pnm_fread_rgb(FILE * L1_f)
{
TRACE_PUSH("C_pnm_fread_rgb"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(3);
storage_t *L2_0_srg = new_storage(ST_UCHAR);
{
index_t * L2_1_u;
(L2_0_array)->st = L2_0_srg;
Midx_init_dim3(L2_0_array, 1,1,3);
RTERR_DIM(L2_0_array->dim[0]<0);
RTERR_DIM(L2_0_array->dim[1]<0);
RTERR_DIM(L2_0_array->dim[2]<0);
Midx_maclear(L2_0_array, unsigned char );
L2_1_u = L2_0_array;
C_pnm_fread_into_rgbx(L1_f, L2_1_u);
L_Tmp0 = L2_1_u;
}
TRACE_POP("C_pnm_fread_rgb");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION pnm-read-rgb
 */
extern_c index_t * C_pnm_read_rgb(char* L1_s)
{
TRACE_PUSH("C_pnm_read_rgb"); MM_ENTER;
{
index_t * L_Tmp0;
{
FILE * L2_1_f;
index_t * L_Tmp2_prog1ret;
char *L2_0_str;
Mstr_alloc(L2_0_str, 2+1);
strcpy((char*)(L2_0_str),"rb");
L2_1_f = (gptr ) C_fopen(L1_s, L2_0_str);
 if (!(L2_1_f)) { 
lush_error("couldn't open PNM file");
 } 
L_Tmp2_prog1ret = (index_t * ) C_pnm_fread_rgb(L2_1_f);
MM_ANCHOR(L_Tmp2_prog1ret);
C_fclose(L2_1_f);
L_Tmp0 = L_Tmp2_prog1ret;
}
TRACE_POP("C_pnm_read_rgb");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION pnm-fread-rgba
 */
extern_c index_t * C_pnm_fread_rgba(FILE * L1_f)
{
TRACE_PUSH("C_pnm_fread_rgba"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(3);
storage_t *L2_0_srg = new_storage(ST_UCHAR);
{
index_t * L2_1_u;
Midx_declare(L2_2_1_select, 2);
Midx_init(L2_2_1_select, 2);
(L2_0_array)->st = L2_0_srg;
Midx_init_dim3(L2_0_array, 1,1,4);
RTERR_DIM(L2_0_array->dim[0]<0);
RTERR_DIM(L2_0_array->dim[1]<0);
RTERR_DIM(L2_0_array->dim[2]<0);
Midx_maclear(L2_0_array, unsigned char );
L2_1_u = L2_0_array;
C_pnm_fread_into_rgbx(L1_f, L2_1_u);
RTERR_GEN((((int)3) >= ((int)(L2_1_u)->dim[((int)2)])), "idx-select: subscript is too large");
Midx_select(L2_2_1_select,L2_1_u,((int)2),((int)3),unsigned char );
Midx_m2clearwith(L2_2_1_select,0,unsigned char );
L_Tmp0 = L2_1_u;
}
TRACE_POP("C_pnm_fread_rgba");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION pnm-read-rgba
 */
extern_c index_t * C_pnm_read_rgba(char* L1_s)
{
TRACE_PUSH("C_pnm_read_rgba"); MM_ENTER;
{
index_t * L_Tmp0;
{
FILE * L2_1_f;
index_t * L_Tmp2_prog1ret;
char *L2_0_str;
Mstr_alloc(L2_0_str, 2+1);
strcpy((char*)(L2_0_str),"rb");
L2_1_f = (gptr ) C_fopen(L1_s, L2_0_str);
 if (!(L2_1_f)) { 
lush_error("couldn't open PNM file");
 } 
L_Tmp2_prog1ret = (index_t * ) C_pnm_fread_rgba(L2_1_f);
MM_ANCHOR(L_Tmp2_prog1ret);
C_fclose(L2_1_f);
L_Tmp0 = L_Tmp2_prog1ret;
}
TRACE_POP("C_pnm_read_rgba");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION pnm-fread-into-ubim
 */
extern_c bool C_pnm_fread_into_ubim(FILE * L1_f,index_t * L1_out)
{
TRACE_PUSH("C_pnm_fread_into_ubim"); MM_ENTER;
{
{
char* L2_0_head;
int L2_1_nlino;
int L2_2_ncolo;
L2_0_head = (char* ) C_pnm_header(L1_f);
RTERR_DIM(0 < 0 || 0 >= 2);
L2_1_nlino = (L1_out)->dim[0];
RTERR_DIM(1 < 0 || 1 >= 2);
L2_2_ncolo = (L1_out)->dim[1];
char *L2_0_str;
Mstr_alloc(L2_0_str, 2+1);
strcpy((char*)(L2_0_str),"P4");
 if ((strcmp((L2_0_head), (L2_0_str)) == 0)) { 
{
int L3_3_ncol;
int L3_4_nlin;
int L3_5_n;
int L3_6_c;
bool L_Tmp7;
L3_3_ncol = (int ) C_fscan_int(L1_f);
L3_4_nlin = (int ) C_fscan_int(L1_f);
L3_5_n = 0;
L3_6_c = 0;
 if ((L3_3_ncol!=L2_2_ncolo)) { 
L_Tmp7 = true;
 } else { 
 if ((L3_4_nlin!=L2_1_nlino)) { 
L_Tmp7 = true;
 } else { 
L_Tmp7 = 0;
 } 
 } 
 if (L_Tmp7) { 
C_idx_u2resize(L1_out, L3_4_nlin, L3_3_ncol);
 } 
C_fgetc(L1_f);
{ register unsigned char *_idx2loopc, *p;
  register int i, _imax = (L1_out)->dim[0];
  register int j, _jmax = (L1_out)->dim[1];
  register int _imat1_m0 = (L1_out)->mod[0];
  register int _imat1_m1 = (L1_out)->mod[1];
    _idx2loopc = IDX_PTR((L1_out),unsigned char);
  for (i=0; i <_imax; i++){;
    p= _idx2loopc;
    for (j=0; j <_jmax; j++){;
{ unsigned char v;
	        if ((j == 0) || ((L3_5_n) == 0)) { (L3_6_c) = getc((FILE *)(L1_f)); (L3_5_n)=0; }
		v = ((L3_6_c) & 128) ? 0 : 255 ;
		*p = v;
		(L3_5_n) = ((L3_5_n) == 7) ? 0 : (L3_5_n)+1 ;
		(L3_6_c) = (L3_6_c) << 1; 
	     }
    p += _imat1_m1;
    }
     _idx2loopc += _imat1_m0;
  } }
}
 } else { 
char *L2_1_str;
Mstr_alloc(L2_1_str, 2+1);
strcpy((char*)(L2_1_str),"P5");
 if ((strcmp((L2_0_head), (L2_1_str)) == 0)) { 
{
int L3_8_ncol;
int L3_9_nlin;
bool L_Tmp10;
L3_8_ncol = (int ) C_fscan_int(L1_f);
L3_9_nlin = (int ) C_fscan_int(L1_f);
 if ((L3_8_ncol!=L2_2_ncolo)) { 
L_Tmp10 = true;
 } else { 
 if ((L3_9_nlin!=L2_1_nlino)) { 
L_Tmp10 = true;
 } else { 
L_Tmp10 = 0;
 } 
 } 
 if (L_Tmp10) { 
C_idx_u2resize(L1_out, L3_9_nlin, L3_8_ncol);
 } 
C_fscan_int(L1_f);
C_fgetc(L1_f);
{ register unsigned char *_idx2loopc, *p;
  register int i, _imax = (L1_out)->dim[0];
  register int j, _jmax = (L1_out)->dim[1];
  register int _imat1_m0 = (L1_out)->mod[0];
  register int _imat1_m1 = (L1_out)->mod[1];
    _idx2loopc = IDX_PTR((L1_out),unsigned char);
  for (i=0; i <_imax; i++){;
    p= _idx2loopc;
    for (j=0; j <_jmax; j++){;
{ *p=getc((FILE *)(L1_f)); }
    p += _imat1_m1;
    }
     _idx2loopc += _imat1_m0;
  } }
}
 } else { 
char *L2_2_str;
Mstr_alloc(L2_2_str, 2+1);
strcpy((char*)(L2_2_str),"P6");
 if ((strcmp((L2_0_head), (L2_2_str)) == 0)) { 
{
int L3_11_ncol;
int L3_12_nlin;
bool L_Tmp13;
L3_11_ncol = (int ) C_fscan_int(L1_f);
L3_12_nlin = (int ) C_fscan_int(L1_f);
 if ((L3_11_ncol!=L2_2_ncolo)) { 
L_Tmp13 = true;
 } else { 
 if ((L3_12_nlin!=L2_1_nlino)) { 
L_Tmp13 = true;
 } else { 
L_Tmp13 = 0;
 } 
 } 
 if (L_Tmp13) { 
C_idx_u2resize(L1_out, L3_12_nlin, L3_11_ncol);
 } 
C_fscan_int(L1_f);
C_fgetc(L1_f);
{ register unsigned char *_idx2loopc, *p;
  register int i, _imax = (L1_out)->dim[0];
  register int j, _jmax = (L1_out)->dim[1];
  register int _imat1_m0 = (L1_out)->mod[0];
  register int _imat1_m1 = (L1_out)->mod[1];
    _idx2loopc = IDX_PTR((L1_out),unsigned char);
  for (i=0; i <_imax; i++){;
    p= _idx2loopc;
    for (j=0; j <_jmax; j++){;
{ register float v; 
	        v = 0.299 * (flt)(getc((FILE *)(L1_f))) +
		    0.587 * (flt)(getc((FILE *)(L1_f))) +
		    0.114 * (flt)(getc((FILE *)(L1_f))) ; 
	        *p = (unsigned char)( (v>255) ? 255 : ( (v<0) ? 0 : v ));
              }
    p += _imat1_m1;
    }
     _idx2loopc += _imat1_m0;
  } }
}
 } else { 
 } 
 } 
 } 
}
TRACE_POP("C_pnm_fread_into_ubim");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION pnm-read-into-ubim
 */
extern_c bool C_pnm_read_into_ubim(char* L1_s,index_t * L1_out)
{
TRACE_PUSH("C_pnm_read_into_ubim"); MM_ENTER;
{
{
FILE * L2_0_f;
char *L2_0_str;
Mstr_alloc(L2_0_str, 2+1);
strcpy((char*)(L2_0_str),"rb");
L2_0_f = (gptr ) C_fopen(L1_s, L2_0_str);
 if (!(L2_0_f)) { 
lush_error("couldn't open PNM file");
 } 
C_pnm_fread_into_ubim(L2_0_f, L1_out);
C_fclose(L2_0_f);
}
TRACE_POP("C_pnm_read_into_ubim");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION pnm-fread-ubim
 */
extern_c index_t * C_pnm_fread_ubim(FILE * L1_f)
{
TRACE_PUSH("C_pnm_fread_ubim"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(2);
storage_t *L2_0_srg = new_storage(ST_UCHAR);
{
index_t * L2_1_u;
(L2_0_array)->st = L2_0_srg;
Midx_init_dim2(L2_0_array, 1,1);
RTERR_DIM(L2_0_array->dim[0]<0);
RTERR_DIM(L2_0_array->dim[1]<0);
Midx_maclear(L2_0_array, unsigned char );
L2_1_u = L2_0_array;
C_pnm_fread_into_ubim(L1_f, L2_1_u);
L_Tmp0 = L2_1_u;
}
TRACE_POP("C_pnm_fread_ubim");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION pnm-read-ubim
 */
extern_c index_t * C_pnm_read_ubim(char* L1_s)
{
TRACE_PUSH("C_pnm_read_ubim"); MM_ENTER;
{
index_t * L_Tmp0;
{
FILE * L2_1_f;
index_t * L_Tmp2_prog1ret;
char *L2_0_str;
Mstr_alloc(L2_0_str, 2+1);
strcpy((char*)(L2_0_str),"rb");
L2_1_f = (gptr ) C_fopen(L1_s, L2_0_str);
 if (!(L2_1_f)) { 
lush_error("couldn't open PNM file");
 } 
L_Tmp2_prog1ret = (index_t * ) C_pnm_fread_ubim(L2_1_f);
MM_ANCHOR(L_Tmp2_prog1ret);
C_fclose(L2_1_f);
L_Tmp0 = L_Tmp2_prog1ret;
}
TRACE_POP("C_pnm_read_ubim");
MM_EXIT; return L_Tmp0;
}
}

/*
 * FUNCTION ppm-mmap
 */
extern_c index_t * C_ppm_mmap(FILE * L1_f)
{
TRACE_PUSH("C_ppm_mmap"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(3);
storage_t *L2_0_srg = new_storage(ST_UCHAR);
{
index_t * L2_1_u;
char* L2_2_head;
(L2_0_array)->st = L2_0_srg;
Midx_init_dim3(L2_0_array, 0,0,3);
RTERR_DIM(L2_0_array->dim[0]<0);
RTERR_DIM(L2_0_array->dim[1]<0);
RTERR_DIM(L2_0_array->dim[2]<0);
Midx_maclear(L2_0_array, unsigned char );
L2_1_u = L2_0_array;
L2_2_head = (char* ) C_pnm_header(L1_f);
char *L2_1_str;
Mstr_alloc(L2_1_str, 2+1);
strcpy((char*)(L2_1_str),"P6");
 if ((strcmp((L2_2_head), (L2_1_str)) != 0)) { 
lush_error("must mmap a PPM file");
 } else { 
{
int L3_3_ncol;
int L3_4_nlin;
bool L_Tmp5;
L3_3_ncol = (int ) C_fscan_int(L1_f);
L3_4_nlin = (int ) C_fscan_int(L1_f);
C_fscan_int(L1_f);
C_fgetc(L1_f);
L_Tmp5 = (bool ) C_mmap_idx3_storage(L1_f, L2_1_u, L3_4_nlin, L3_3_ncol, 3);
 if (!(L_Tmp5)) { 
printf("%s", "\"Could not MMAP file, i'll just load it\"");
printf("\n");
C_pnm_fread_into_rgbx(L1_f, L2_1_u);
 } 
}
 } 
L_Tmp0 = L2_1_u;
}
TRACE_POP("C_ppm_mmap");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION pgm-mmap
 */
extern_c index_t * C_pgm_mmap(FILE * L1_f)
{
TRACE_PUSH("C_pgm_mmap"); MM_ENTER;
{
index_t * L_Tmp0;
index_t *L2_0_array = new_empty_index(2);
storage_t *L2_0_srg = new_storage(ST_UCHAR);
{
index_t * L2_1_u;
char* L2_2_head;
(L2_0_array)->st = L2_0_srg;
Midx_init_dim2(L2_0_array, 0,0);
RTERR_DIM(L2_0_array->dim[0]<0);
RTERR_DIM(L2_0_array->dim[1]<0);
Midx_maclear(L2_0_array, unsigned char );
L2_1_u = L2_0_array;
L2_2_head = (char* ) C_pnm_header(L1_f);
char *L2_1_str;
Mstr_alloc(L2_1_str, 2+1);
strcpy((char*)(L2_1_str),"P5");
 if ((strcmp((L2_2_head), (L2_1_str)) != 0)) { 
lush_error("must mmap a PGM file");
 } else { 
{
int L3_3_ncol;
int L3_4_nlin;
bool L_Tmp5;
L3_3_ncol = (int ) C_fscan_int(L1_f);
L3_4_nlin = (int ) C_fscan_int(L1_f);
C_fscan_int(L1_f);
C_fgetc(L1_f);
L_Tmp5 = (bool ) C_mmap_idx2_storage(L1_f, L2_1_u, L3_4_nlin, L3_3_ncol);
 if (!(L_Tmp5)) { 
printf("%s", "\"Could not MMAP file, i'll just load it\"");
printf("\n");
C_pnm_fread_into_ubim(L1_f, L2_1_u);
 } 
}
 } 
L_Tmp0 = L2_1_u;
}
TRACE_POP("C_pgm_mmap");
MM_EXIT; MM_ANCHOR(L_Tmp0); return L_Tmp0;
}
}

/*
 * FUNCTION ppm-fwrite-rgb
 */
extern_c bool C_ppm_fwrite_rgb(FILE * L1_f,index_t * L1_m)
{
TRACE_PUSH("C_ppm_fwrite_rgb"); MM_ENTER;
{
bool L_Tmp0;
{
int L2_1_nlin;
int L2_2_ncol;
RTERR_DIM(0 < 0 || 0 >= 3);
L2_1_nlin = (L1_m)->dim[0];
RTERR_DIM(1 < 0 || 1 >= 3);
L2_2_ncol = (L1_m)->dim[1];
 fprintf((FILE *)(L1_f),"P6 %d %d 255\n",(L2_2_ncol),(L2_1_nlin));
{ register unsigned char *_idx2loopc, *p;
  register int i, _imax = (L1_m)->dim[0];
  register int j, _jmax = (L1_m)->dim[1];
  register int _imat1_m0 = (L1_m)->mod[0];
  register int _imat1_m1 = (L1_m)->mod[1];
    _idx2loopc = IDX_PTR((L1_m),unsigned char);
  for (i=0; i <_imax; i++){;
    p= _idx2loopc;
    for (j=0; j <_jmax; j++){;
 putc(p[0], (FILE *)(L1_f)); 
           putc(p[1], (FILE *)(L1_f)); 
           putc(p[2], (FILE *)(L1_f));
    p += _imat1_m1;
    }
     _idx2loopc += _imat1_m0;
  } }
L_Tmp0 = 0;
}
TRACE_POP("C_ppm_fwrite_rgb");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION ppm-write-rgb
 */
extern_c bool C_ppm_write_rgb(char* L1_f,index_t * L1_m)
{
TRACE_PUSH("C_ppm_write_rgb"); MM_ENTER;
{
bool L_Tmp0;
{
FILE * L2_1_f;
char *L2_0_str;
Mstr_alloc(L2_0_str, 2+1);
strcpy((char*)(L2_0_str),"wb");
L2_1_f = (gptr ) C_fopen(L1_f, L2_0_str);
 if (!(L2_1_f)) { 
lush_error("couldn't open PPM file");
 } 
C_ppm_fwrite_rgb(L2_1_f, L1_m);
C_fclose(L2_1_f);
L_Tmp0 = 0;
}
TRACE_POP("C_ppm_write_rgb");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION pgm-fwrite-ubim
 */
extern_c bool C_pgm_fwrite_ubim(FILE * L1_f,index_t * L1_m)
{
TRACE_PUSH("C_pgm_fwrite_ubim"); MM_ENTER;
{
bool L_Tmp0;
{
int L2_1_nlin;
int L2_2_ncol;
RTERR_DIM(0 < 0 || 0 >= 2);
L2_1_nlin = (L1_m)->dim[0];
RTERR_DIM(1 < 0 || 1 >= 2);
L2_2_ncol = (L1_m)->dim[1];
 fprintf((FILE *)(L1_f),"P5 %d %d 255\n",(L2_2_ncol),(L2_1_nlin));
{ register unsigned char *_idx2loopc, *p;
  register int i, _imax = (L1_m)->dim[0];
  register int j, _jmax = (L1_m)->dim[1];
  register int _imat1_m0 = (L1_m)->mod[0];
  register int _imat1_m1 = (L1_m)->mod[1];
    _idx2loopc = IDX_PTR((L1_m),unsigned char);
  for (i=0; i <_imax; i++){;
    p= _idx2loopc;
    for (j=0; j <_jmax; j++){;
 putc(*p, (FILE *)(L1_f));
    p += _imat1_m1;
    }
     _idx2loopc += _imat1_m0;
  } }
L_Tmp0 = 0;
}
TRACE_POP("C_pgm_fwrite_ubim");
MM_EXIT; return 0;
}
}

/*
 * FUNCTION pgm-write-ubim
 */
extern_c bool C_pgm_write_ubim(char* L1_f,index_t * L1_m)
{
TRACE_PUSH("C_pgm_write_ubim"); MM_ENTER;
{
bool L_Tmp0;
{
FILE * L2_1_f;
char *L2_0_str;
Mstr_alloc(L2_0_str, 2+1);
strcpy((char*)(L2_0_str),"wb");
L2_1_f = (gptr ) C_fopen(L1_f, L2_0_str);
 if (!(L2_1_f)) { 
lush_error("couldn't open PGM file");
 } 
C_pgm_fwrite_ubim(L2_1_f, L1_m);
C_fclose(L2_1_f);
L_Tmp0 = 0;
}
TRACE_POP("C_pgm_write_ubim");
MM_EXIT; return 0;
}
}

/* ---------------------------------------- */

#ifndef NOLISP

/* Declarations */
extern_c dhdoc_t K_rewind_Rc7df00c0;
extern_c dhdoc_t K_fscan_str_R6df7e29f;
extern_c dhdoc_t K_fclose_Rc7df00c0;
extern_c dhdoc_t K_skip_comments_Rd00b086e;
extern_c dhdoc_t K_idx_u3resize_Refd75d8e;
extern_c dhdoc_t K_idx_u2resize_R24b748bc;
extern_c dhdoc_t K_fscan_int_R6d6f2621;
extern_c dhdoc_t K_fgetc_R6d6f2621;
extern_c dhdoc_t K_fopen_Rc8f18d7f;


/*
 * STUB pnm-dummy
 */
DH(X_pnm_dummy)
{
dharg ret;
ret.dh_bool =  C_pnm_dummy();
return ret;
}

/*
 * DHDOC pnm-dummy
 */
DHDOC(K_pnm_dummy_Ra8b05737,X_pnm_dummy,"C_pnm_dummy",0,0) = {
DH_FUNC(0),
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB pnm-header
 */
DH(X_pnm_header)
{
dharg ret;
ret.dh_str_ptr =  C_pnm_header((FILE * )a[1].dh_gptr);
return ret;
}

/*
 * DHDOC pnm-header
 */
DHDOC(K_pnm_header_R6df7e29f,X_pnm_header,"C_pnm_header",0,0) = {
DH_FUNC(1),
DH_GPTR("FILE *"),
DH_RETURN,
DH_STR,
DH_END_FUNC,
DH_REFER(K_rewind_Rc7df00c0),
DH_REFER(K_fscan_str_R6df7e29f),
DH_REFER(K_fclose_Rc7df00c0),
DH_REFER(K_skip_comments_Rd00b086e),
DH_NIL
};

/*
 * STUB mmap-idx3-storage
 */
DH(X_mmap_idx3_storage)
{
dharg ret;
ret.dh_bool =  C_mmap_idx3_storage((FILE * )a[1].dh_gptr, a[2].dh_idx_ptr, a[3].dh_int, a[4].dh_int, a[5].dh_int);
return ret;
}

/*
 * DHDOC mmap-idx3-storage
 */
DHDOC(K_mmap_idx3_storage_R192222f8,X_mmap_idx3_storage,"C_mmap_idx3_storage",0,0) = {
DH_FUNC(5),
DH_GPTR("FILE *"),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_INT,
DH_INT,
DH_INT,
DH_RETURN,
DH_BOOL,
DH_END_FUNC,
DH_REFER(K_idx_u3resize_Refd75d8e),
DH_NIL
};

/*
 * STUB mmap-idx2-storage
 */
DH(X_mmap_idx2_storage)
{
dharg ret;
ret.dh_bool =  C_mmap_idx2_storage((FILE * )a[1].dh_gptr, a[2].dh_idx_ptr, a[3].dh_int, a[4].dh_int);
return ret;
}

/*
 * DHDOC mmap-idx2-storage
 */
DHDOC(K_mmap_idx2_storage_R5fcdf707,X_mmap_idx2_storage,"C_mmap_idx2_storage",0,0) = {
DH_FUNC(4),
DH_GPTR("FILE *"),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_INT,
DH_INT,
DH_RETURN,
DH_BOOL,
DH_END_FUNC,
DH_REFER(K_idx_u2resize_R24b748bc),
DH_NIL
};

/*
 * STUB pnm-fread-into-rgbx
 */
DH(X_pnm_fread_into_rgbx)
{
dharg ret;
ret.dh_bool =  C_pnm_fread_into_rgbx((FILE * )a[1].dh_gptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC pnm-fread-into-rgbx
 */
DHDOC(K_pnm_fread_into_rgbx_R2d01e887,X_pnm_fread_into_rgbx,"C_pnm_fread_into_rgbx",0,0) = {
DH_FUNC(2),
DH_GPTR("FILE *"),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_REFER(K_idx_u3resize_Refd75d8e),
DH_REFER(K_fscan_int_R6d6f2621),
DH_REFER(K_fgetc_R6d6f2621),
DH_NIL
};

/*
 * STUB pnm-read-into-rgbx
 */
DH(X_pnm_read_into_rgbx)
{
dharg ret;
ret.dh_bool =  C_pnm_read_into_rgbx(a[1].dh_str_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC pnm-read-into-rgbx
 */
DHDOC(K_pnm_read_into_rgbx_R448167d5,X_pnm_read_into_rgbx,"C_pnm_read_into_rgbx",0,0) = {
DH_FUNC(2),
DH_STR,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_REFER(K_fopen_Rc8f18d7f),
DH_REFER(K_fclose_Rc7df00c0),
DH_NIL
};

/*
 * STUB pnm-fread-rgb
 */
DH(X_pnm_fread_rgb)
{
dharg ret;
ret.dh_idx_ptr =  C_pnm_fread_rgb((FILE * )a[1].dh_gptr);
return ret;
}

/*
 * DHDOC pnm-fread-rgb
 */
DHDOC(K_pnm_fread_rgb_R6defe29f,X_pnm_fread_rgb,"C_pnm_fread_rgb",0,0) = {
DH_FUNC(1),
DH_GPTR("FILE *"),
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB pnm-read-rgb
 */
DH(X_pnm_read_rgb)
{
dharg ret;
ret.dh_idx_ptr =  C_pnm_read_rgb(a[1].dh_str_ptr);
return ret;
}

/*
 * DHDOC pnm-read-rgb
 */
DHDOC(K_pnm_read_rgb_R592fa536,X_pnm_read_rgb,"C_pnm_read_rgb",0,0) = {
DH_FUNC(1),
DH_STR,
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_END_FUNC,
DH_REFER(K_fopen_Rc8f18d7f),
DH_REFER(K_fclose_Rc7df00c0),
DH_NIL
};

/*
 * STUB pnm-fread-rgba
 */
DH(X_pnm_fread_rgba)
{
dharg ret;
ret.dh_idx_ptr =  C_pnm_fread_rgba((FILE * )a[1].dh_gptr);
return ret;
}

/*
 * DHDOC pnm-fread-rgba
 */
DHDOC(K_pnm_fread_rgba_R6defe29f,X_pnm_fread_rgba,"C_pnm_fread_rgba",0,0) = {
DH_FUNC(1),
DH_GPTR("FILE *"),
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_WRITE),
DH_UCHAR,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB pnm-read-rgba
 */
DH(X_pnm_read_rgba)
{
dharg ret;
ret.dh_idx_ptr =  C_pnm_read_rgba(a[1].dh_str_ptr);
return ret;
}

/*
 * DHDOC pnm-read-rgba
 */
DHDOC(K_pnm_read_rgba_R592fa536,X_pnm_read_rgba,"C_pnm_read_rgba",0,0) = {
DH_FUNC(1),
DH_STR,
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_WRITE),
DH_UCHAR,
DH_END_FUNC,
DH_REFER(K_fopen_Rc8f18d7f),
DH_REFER(K_fclose_Rc7df00c0),
DH_NIL
};

/*
 * STUB pnm-fread-into-ubim
 */
DH(X_pnm_fread_into_ubim)
{
dharg ret;
ret.dh_bool =  C_pnm_fread_into_ubim((FILE * )a[1].dh_gptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC pnm-fread-into-ubim
 */
DHDOC(K_pnm_fread_into_ubim_R2d01e887,X_pnm_fread_into_ubim,"C_pnm_fread_into_ubim",0,0) = {
DH_FUNC(2),
DH_GPTR("FILE *"),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_REFER(K_idx_u2resize_R24b748bc),
DH_REFER(K_fscan_int_R6d6f2621),
DH_REFER(K_fgetc_R6d6f2621),
DH_NIL
};

/*
 * STUB pnm-read-into-ubim
 */
DH(X_pnm_read_into_ubim)
{
dharg ret;
ret.dh_bool =  C_pnm_read_into_ubim(a[1].dh_str_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC pnm-read-into-ubim
 */
DHDOC(K_pnm_read_into_ubim_R448167d5,X_pnm_read_into_ubim,"C_pnm_read_into_ubim",0,0) = {
DH_FUNC(2),
DH_STR,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_REFER(K_fopen_Rc8f18d7f),
DH_REFER(K_fclose_Rc7df00c0),
DH_NIL
};

/*
 * STUB pnm-fread-ubim
 */
DH(X_pnm_fread_ubim)
{
dharg ret;
ret.dh_idx_ptr =  C_pnm_fread_ubim((FILE * )a[1].dh_gptr);
return ret;
}

/*
 * DHDOC pnm-fread-ubim
 */
DHDOC(K_pnm_fread_ubim_R6defe29f,X_pnm_fread_ubim,"C_pnm_fread_ubim",0,0) = {
DH_FUNC(1),
DH_GPTR("FILE *"),
DH_RETURN,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB pnm-read-ubim
 */
DH(X_pnm_read_ubim)
{
dharg ret;
ret.dh_idx_ptr =  C_pnm_read_ubim(a[1].dh_str_ptr);
return ret;
}

/*
 * DHDOC pnm-read-ubim
 */
DHDOC(K_pnm_read_ubim_R592fa536,X_pnm_read_ubim,"C_pnm_read_ubim",0,0) = {
DH_FUNC(1),
DH_STR,
DH_RETURN,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_END_FUNC,
DH_REFER(K_fopen_Rc8f18d7f),
DH_REFER(K_fclose_Rc7df00c0),
DH_NIL
};

/*
 * STUB ppm-mmap
 */
DH(X_ppm_mmap)
{
dharg ret;
ret.dh_idx_ptr =  C_ppm_mmap((FILE * )a[1].dh_gptr);
return ret;
}

/*
 * DHDOC ppm-mmap
 */
DHDOC(K_ppm_mmap_R6defe29f,X_ppm_mmap,"C_ppm_mmap",0,0) = {
DH_FUNC(1),
DH_GPTR("FILE *"),
DH_RETURN,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_END_FUNC,
DH_REFER(K_fscan_int_R6d6f2621),
DH_REFER(K_fgetc_R6d6f2621),
DH_NIL
};

/*
 * STUB pgm-mmap
 */
DH(X_pgm_mmap)
{
dharg ret;
ret.dh_idx_ptr =  C_pgm_mmap((FILE * )a[1].dh_gptr);
return ret;
}

/*
 * DHDOC pgm-mmap
 */
DHDOC(K_pgm_mmap_R6defe29f,X_pgm_mmap,"C_pgm_mmap",0,0) = {
DH_FUNC(1),
DH_GPTR("FILE *"),
DH_RETURN,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_END_FUNC,
DH_REFER(K_fscan_int_R6d6f2621),
DH_REFER(K_fgetc_R6d6f2621),
DH_NIL
};

/*
 * STUB ppm-fwrite-rgb
 */
DH(X_ppm_fwrite_rgb)
{
dharg ret;
ret.dh_bool =  C_ppm_fwrite_rgb((FILE * )a[1].dh_gptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC ppm-fwrite-rgb
 */
DHDOC(K_ppm_fwrite_rgb_R2d01e887,X_ppm_fwrite_rgb,"C_ppm_fwrite_rgb",0,0) = {
DH_FUNC(2),
DH_GPTR("FILE *"),
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB ppm-write-rgb
 */
DH(X_ppm_write_rgb)
{
dharg ret;
ret.dh_bool =  C_ppm_write_rgb(a[1].dh_str_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC ppm-write-rgb
 */
DHDOC(K_ppm_write_rgb_R448167d5,X_ppm_write_rgb,"C_ppm_write_rgb",0,0) = {
DH_FUNC(2),
DH_STR,
DH_IDX(DHT_READ,3),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_REFER(K_fopen_Rc8f18d7f),
DH_REFER(K_fclose_Rc7df00c0),
DH_NIL
};

/*
 * STUB pgm-fwrite-ubim
 */
DH(X_pgm_fwrite_ubim)
{
dharg ret;
ret.dh_bool =  C_pgm_fwrite_ubim((FILE * )a[1].dh_gptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC pgm-fwrite-ubim
 */
DHDOC(K_pgm_fwrite_ubim_R2d01e887,X_pgm_fwrite_ubim,"C_pgm_fwrite_ubim",0,0) = {
DH_FUNC(2),
DH_GPTR("FILE *"),
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_NIL
};

/*
 * STUB pgm-write-ubim
 */
DH(X_pgm_write_ubim)
{
dharg ret;
ret.dh_bool =  C_pgm_write_ubim(a[1].dh_str_ptr, a[2].dh_idx_ptr);
return ret;
}

/*
 * DHDOC pgm-write-ubim
 */
DHDOC(K_pgm_write_ubim_R448167d5,X_pgm_write_ubim,"C_pgm_write_ubim",0,0) = {
DH_FUNC(2),
DH_STR,
DH_IDX(DHT_READ,2),
DH_SRG(DHT_READ),
DH_UCHAR,
DH_RETURN,
DH_NIL,
DH_END_FUNC,
DH_REFER(K_fopen_Rc8f18d7f),
DH_REFER(K_fclose_Rc7df00c0),
DH_NIL
};

/*
 * INIT FUNCTION
 */
extern_c void init_pnm(void)
{
 dh_define("pnm-dummy", &K_pnm_dummy_Ra8b05737); 
 dh_define("pnm-header", &K_pnm_header_R6df7e29f); 
 dh_define("mmap-idx3-storage", &K_mmap_idx3_storage_R192222f8); 
 dh_define("mmap-idx2-storage", &K_mmap_idx2_storage_R5fcdf707); 
 dh_define("pnm-fread-into-rgbx", &K_pnm_fread_into_rgbx_R2d01e887); 
 dh_define("pnm-read-into-rgbx", &K_pnm_read_into_rgbx_R448167d5); 
 dh_define("pnm-fread-rgb", &K_pnm_fread_rgb_R6defe29f); 
 dh_define("pnm-read-rgb", &K_pnm_read_rgb_R592fa536); 
 dh_define("pnm-fread-rgba", &K_pnm_fread_rgba_R6defe29f); 
 dh_define("pnm-read-rgba", &K_pnm_read_rgba_R592fa536); 
 dh_define("pnm-fread-into-ubim", &K_pnm_fread_into_ubim_R2d01e887); 
 dh_define("pnm-read-into-ubim", &K_pnm_read_into_ubim_R448167d5); 
 dh_define("pnm-fread-ubim", &K_pnm_fread_ubim_R6defe29f); 
 dh_define("pnm-read-ubim", &K_pnm_read_ubim_R592fa536); 
 dh_define("ppm-mmap", &K_ppm_mmap_R6defe29f); 
 dh_define("pgm-mmap", &K_pgm_mmap_R6defe29f); 
 dh_define("ppm-fwrite-rgb", &K_ppm_fwrite_rgb_R2d01e887); 
 dh_define("ppm-write-rgb", &K_ppm_write_rgb_R448167d5); 
 dh_define("pgm-fwrite-ubim", &K_pgm_fwrite_ubim_R2d01e887); 
 dh_define("pgm-write-ubim", &K_pgm_write_ubim_R448167d5); 
}

int majver_pnm = 50;
int minver_pnm = 01;


#endif

